<?php
declare(strict_types=1);

namespace Automattic\SiteBuild\Steps;

use Automattic\SiteBuild\BlockMarkup;
use Automattic\SiteBuild\Llm;
use Automattic\SiteBuild\LlmOptions;
use Automattic\SiteBuild\Project;
use Automattic\SiteBuild\PromptRenderer;
use Automattic\SiteBuild\Step;

/**
 * Step (LLM, optional): implement an EXPLICIT user animation request.
 *
 * Input:  siteSpec.json (`animation_request`, captured verbatim by site-spec)
 *         + the final markup (AFTER fix-blocks, where the section, header, or
 *         footer prompt tagged the target with the `custom-motion` class).
 * Output: a small CSS block appended to theme/style.css, wrapped in
 *         @media (prefers-reduced-motion: no-preference).
 *
 * This is the escape hatch to the motion system's core rule ("the LLM never
 * writes animation CSS"): only when the user literally asked for a specific
 * behavior the preset kit cannot express ("the logo should spin on hover")
 * does one scoped generation call run. In the default path the step no-ops
 * without any LLM call — an empty `animation_request`, or a request whose
 * `custom-motion` tag never made it into the markup, costs zero tokens.
 *
 * The generated CSS gets a relaxed version of the page-styles validation:
 * @keyframes ARE allowed (names must start with `custom-motion-`), but every
 * selector must live under `.custom-motion`, nothing may hide content at rest
 * (no display:none / visibility:hidden anywhere; zero opacity only in a
 * `from`/`0%` keyframe step, so an entrance can start invisible but nothing
 * can END hidden), no resource-loading value forms (url(), image-set(), …) or
 * @import/@font-face, and the whole block is capped.
 * Rejected CSS is logged and skipped — the build never fails over decoration.
 */
final class CustomMotionStep implements Step
{
    use LlmOptions;

    /** The markup class the section/header/footer prompts tag request targets with. */
    public const CLASS_NAME = 'custom-motion';

    private const MAX_LINES = 60;
    private const LOG_FILE = 'custom-motion.log';
    private const MARKER = '/* Custom motion — user-requested animation, generated by the custom-motion step. */';

    public function __construct(
        private Llm $llm,
        private PromptRenderer $renderer,
        private ?string $model = null,
        private ?float $temperature = null,
    ) {}

    public function id(): string
    {
        return 'custom-motion';
    }

    public function label(): string
    {
        return 'Custom motion (explicit requests only)';
    }

    public function run(Project $project): void
    {
        $request = SiteSpecStep::animationRequestOf($project);
        if ($request === '') {
            echo "  no explicit animation request; skipped (no LLM call)\n";
            return;
        }

        $tagged = self::taggedElements($project);
        if ($tagged === []) {
            $message = "animation_request present but no '" . self::CLASS_NAME . "' tag in the markup; skipped";
            file_put_contents($project->logPath(self::LOG_FILE), $message . "\nREQUEST: {$request}\n");
            echo "  custom-motion: {$message} (no LLM call)\n";
            return;
        }

        $rendered = $this->renderer->render('custom-motion.md', [
            'animation_request' => $request,
            'design_direction'  => DesignDirectionStep::readFor($project),
            'tagged_elements'   => implode("\n", $tagged),
        ]);
        $css = self::stripFences(trim(
            $this->llm->complete($rendered, $this->withOptions(['log_label' => $this->id()]))
        ));

        $problems = self::validate($css);
        if ($problems !== []) {
            file_put_contents(
                $project->logPath(self::LOG_FILE),
                "REJECTED CSS:\n{$css}\n\nPROBLEMS:\n- " . implode("\n- ", $problems) . "\n"
            );
            echo '  custom-motion: CSS rejected (' . count($problems)
                . ' problem(s)); skipped — see logs/' . self::LOG_FILE . "\n";
            return;
        }

        // The reduced-motion wrapper is added HERE, deterministically, so a
        // model that forgets it can't ship motion to users who opted out.
        $project->writeText(
            'theme/style.css',
            rtrim($project->readText('theme/style.css'))
            . "\n\n" . self::MARKER
            . "\n@media (prefers-reduced-motion: no-preference) {\n" . $css . "\n}\n"
        );
        echo "  custom-motion: implemented \"{$request}\"\n";
    }

    /**
     * The tagged elements as they appear in the final markup — enough context
     * (tag name, classes) for the model to know what it is animating. For
     * blocks with saved HTML that is the opening tag carrying the class; for
     * dynamic blocks (wp:site-logo, wp:site-title — no saved HTML at all) it
     * is the opening block comment whose "className" carries it. Empty when
     * no step ever placed the class.
     *
     * @return string[]
     */
    public static function taggedElements(Project $project): array
    {
        $found = [];
        $token = '(?<![\w-])' . self::CLASS_NAME . '(?![\w-])';
        foreach (FixBlocksStep::themeFiles($project) as $rel) {
            $doc = BlockMarkup::parse($project->readText('theme/' . $rel));
            foreach ($doc->indices() as $i) {
                if (preg_match_all('/<[a-z][^>]*class="[^"]*' . $token . '[^"]*"[^>]*>/i', $doc->ownHtml($i), $m) > 0) {
                    foreach ($m[0] as $tag) {
                        $found[] = self::clip($tag);
                    }
                    continue;
                }
                $attrs = $doc->attrs($i);
                $className = is_array($attrs) && is_string($attrs['className'] ?? null) ? $attrs['className'] : '';
                if (preg_match('/' . $token . '/', $className) === 1) {
                    $found[] = self::clip($doc->openingComment($i));
                }
            }
        }
        return array_slice($found, 0, 10);
    }

    private static function clip(string $element): string
    {
        return strlen($element) > 300 ? substr($element, 0, 300) . '…' : $element;
    }

    /**
     * The relaxed validation ruleset for user-requested animation CSS.
     * Returns problem strings; empty = valid. Pure — unit-testable.
     *
     * @return string[]
     */
    public static function validate(string $css): array
    {
        $css = trim($css);
        if ($css === '') {
            return ['empty CSS'];
        }

        $problems = [];
        if (substr_count($css, "\n") + 1 > self::MAX_LINES) {
            $problems[] = 'more than ' . self::MAX_LINES . ' lines';
        }

        $stripped = (string) preg_replace('~/\*.*?\*/~s', '', $css);
        // Walk the depth instead of comparing totals: a leading stray `}`
        // (balanced by a trailing open brace) would close the deterministic
        // reduced-motion wrapper this CSS gets concatenated into, letting the
        // rest of the block escape it.
        $depth = 0;
        foreach (str_split($stripped) as $char) {
            if ($char === '{') {
                $depth++;
            } elseif ($char === '}' && --$depth < 0) {
                break;
            }
        }
        if ($depth !== 0) {
            $problems[] = 'unbalanced braces';
            return $problems; // the structural walks below need balanced braces
        }

        // url() is not the only resource-bearing value form: image-set("…"),
        // image("…"), cross-fade() and friends fetch too (including with
        // vendor prefixes, which is why the match is a bare substring).
        if (preg_match('/(?:image-set|cross-fade|element|paint|url|src|image)\s*\(/i', $stripped) === 1) {
            $problems[] = 'resource-loading CSS functions (url(), image-set(), image(), cross-fade(), …) are not allowed';
        }
        if (preg_match('/(?<![-\w])display\s*:\s*none/i', $stripped) === 1) {
            $problems[] = 'display:none hides generated content';
        }
        if (preg_match('/(?<![-\w])visibility\s*:\s*hidden/i', $stripped) === 1) {
            $problems[] = 'visibility:hidden hides generated content';
        }
        if (preg_match_all('/@([a-zA-Z-]+)/', $stripped, $atRules) > 0) {
            foreach (array_unique($atRules[1]) as $at) {
                if (!in_array(strtolower($at), ['media', 'keyframes'], true)) {
                    $problems[] = "disallowed at-rule: @{$at}";
                }
            }
        }

        [$keyframeNames, $rules, $keyframeBodies] = self::stripKeyframes($stripped);
        foreach ($keyframeNames as $name) {
            if (!str_starts_with($name, self::CLASS_NAME . '-')) {
                $problems[] = "keyframe name must start with '" . self::CLASS_NAME . "-': {$name}";
            }
        }

        // Outside keyframes an element must be visible at rest. Parse the
        // value instead of pattern-matching literal zeros: 0%, .0 and calc(0)
        // all hide content just as well as 0.
        if (preg_match_all('/(?<![-\w])opacity\s*:\s*([^;{}]+)/i', $rules, $opacities) > 0) {
            foreach ($opacities[1] as $value) {
                if (self::hidesContent($value)) {
                    $problems[] = 'opacity outside @keyframes must be a plain value above zero: ' . trim($value);
                }
            }
        }

        // Inside keyframes, zero opacity is only ever the transient start of
        // an entrance (`from`/`0%`). In any later step it can be the state a
        // forwards/both fill parks the element in — invisible for good.
        foreach ($keyframeBodies as $body) {
            if (preg_match_all('/([^{}]+)\{([^{}]*)\}/', $body, $steps, PREG_SET_ORDER) === 0) {
                continue;
            }
            foreach ($steps as $step) {
                $selectors = array_map('trim', explode(',', strtolower($step[1])));
                if (array_diff($selectors, ['from', '0%']) === []) {
                    continue;
                }
                if (preg_match_all('/(?<![-\w])opacity\s*:\s*([^;{}]+)/i', $step[2], $opacities) > 0) {
                    foreach ($opacities[1] as $value) {
                        if (self::hidesContent($value)) {
                            $problems[] = 'zero opacity in a non-start keyframe can leave content hidden: '
                                . trim($step[1]) . ' { opacity: ' . trim($value) . ' }';
                        }
                    }
                }
            }
        }

        // Every remaining rule selector must live under the dedicated class.
        $body = (string) preg_replace('/@media[^{]*\{/i', '', $rules);
        if (preg_match_all('/(?:^|[{}])\s*([^{};]+?)\s*\{/s', $body, $m) > 0) {
            foreach ($m[1] as $selectorList) {
                foreach (explode(',', $selectorList) as $selector) {
                    $selector = trim($selector);
                    if (preg_match('/^\.' . self::CLASS_NAME . '(?![\w])/', $selector) !== 1
                        && preg_match('/^\.' . self::CLASS_NAME . '-[\w-]+/', $selector) !== 1
                    ) {
                        $problems[] = "selector not scoped under ." . self::CLASS_NAME . ": {$selector}";
                    }
                }
            }
        }

        return $problems;
    }

    /**
     * Remove @keyframes blocks (brace-aware — they nest) and collect their
     * names and bodies, returning [names, css-without-keyframes, bodies].
     * Pure — unit-testable.
     *
     * @return array{0: string[], 1: string, 2: string[]}
     */
    public static function stripKeyframes(string $css): array
    {
        $names = [];
        $bodies = [];
        $out = '';
        $offset = 0;
        while (preg_match('/@keyframes\s+([\w-]+)\s*\{/i', $css, $m, PREG_OFFSET_CAPTURE, $offset) === 1) {
            $start = $m[0][1];
            $out .= substr($css, $offset, $start - $offset);
            $names[] = $m[1][0];
            $bodyStart = $start + strlen($m[0][0]);
            $i = $bodyStart;
            $depth = 1;
            $length = strlen($css);
            while ($i < $length && $depth > 0) {
                if ($css[$i] === '{') {
                    $depth++;
                } elseif ($css[$i] === '}') {
                    $depth--;
                }
                $i++;
            }
            $bodies[] = substr($css, $bodyStart, max(0, $i - 1 - $bodyStart));
            $offset = $i;
        }
        $out .= substr($css, $offset);
        return [$names, $out, $bodies];
    }

    /**
     * Whether an opacity value hides content: zero in any spelling (0, 0%,
     * .0), or anything that cannot be proven to be a positive plain number
     * (calc(), var(), garbage) — the validator fails closed. Shared with the
     * page-styles validator, which enforces the same visible-at-rest rule.
     */
    public static function hidesContent(string $value): bool
    {
        $value = trim((string) preg_replace('/!important\s*$/i', '', trim($value)));
        if (preg_match('/^(\d*\.?\d+)\s*(%?)$/', $value, $m) !== 1) {
            return true;
        }
        $number = (float) $m[1];
        return ($m[2] === '%' ? $number / 100 : $number) <= 0.0;
    }

    /** Strip a leading/trailing markdown code fence if the model added one. */
    private static function stripFences(string $text): string
    {
        if (str_starts_with($text, '```')) {
            $text = preg_replace('/^```[a-zA-Z]*\n/', '', $text);
            $text = preg_replace('/\n```$/', '', (string) $text);
        }
        return trim((string) $text);
    }
}
