<?php
declare(strict_types=1);

namespace Automattic\SiteBuild\Steps;

use Automattic\SiteBuild\BlockMarkup;
use Automattic\SiteBuild\CodeFences;
use Automattic\SiteBuild\CssChecks;
use Automattic\SiteBuild\Llm;
use Automattic\SiteBuild\LlmOptions;
use Automattic\SiteBuild\Project;
use Automattic\SiteBuild\PromptRenderer;
use Automattic\SiteBuild\Step;
use Automattic\SiteBuild\StepDeclaration;
use Automattic\SiteBuild\Warnings;

/**
 * Step (LLM, optional): implement an EXPLICIT user animation request.
 *
 * Input:  siteSpec.json (`animation_request`, captured verbatim by site-spec)
 *         + the final markup (AFTER fix-blocks, where the section, header, or
 *         footer prompt tagged the target with the `custom-motion` class).
 * Output: a small CSS block appended to theme/style.css, wrapped in
 *         @media screen and (prefers-reduced-motion: no-preference) —
 *         `screen` so print never renders a paused entrance frame.
 *
 * This is the escape hatch to the motion system's core rule ("the LLM never
 * writes animation CSS"): only when the user literally asked for a specific
 * behavior the preset kit cannot express ("the logo should spin on hover")
 * does one scoped generation call run. In the default path the step no-ops
 * without any LLM call — an empty `animation_request`, or a request whose
 * `custom-motion` tag never made it into the markup, costs zero tokens.
 *
 * The generated CSS gets a relaxed version of the page-styles validation:
 * @keyframes ARE allowed (names must start with `custom-motion-`), but every
 * selector must live under `.custom-motion`, nothing may hide content at rest
 * (no display:none / visibility:hidden anywhere; zero opacity only in a
 * `from`/`0%` keyframe step, so an entrance can start invisible but nothing
 * can END hidden), no resource-loading value forms (url(), image-set(), …) or
 * @import/@font-face, and the whole block is capped. Shape-owned radius
 * declarations and profile-owned `--motion-*` custom properties are removed
 * individually before validation so the remaining requested motion can still
 * ship; every removal is recorded durably. Rejected CSS is logged and skipped
 * — the build never fails over decoration.
 */
final class CustomMotionStep implements Step
{
    use LlmOptions;

    /** The markup class the section/header/footer prompts tag request targets with. */
    public const CLASS_NAME = 'custom-motion';

    private const MAX_LINES = 60;
    private const LOG_FILE = 'custom-motion.log';
    private const MARKER = '/* Custom motion — user-requested animation, generated by the custom-motion step. */';

    public function __construct(
        private Llm $llm,
        private PromptRenderer $renderer,
        private ?string $model = null,
        private ?float $temperature = null,
    ) {}

    public function id(): string
    {
        return 'custom-motion';
    }

    public function label(): string
    {
        return 'Custom motion (explicit requests only)';
    }

    public function declaration(): StepDeclaration
    {
        return new StepDeclaration(
            id: $this->id(),
            label: $this->label(),
            reads: ['siteSpec.json', 'designDirection.json', 'theme/style.css', 'theme/parts/*', 'theme/templates/*'],
            writes: ['theme/style.css', 'warnings.json'],
            concurrent: false,
        );
    }

    public function run(Project $project): void
    {
        $request = SiteSpecStep::animationRequestOf($project);
        if ($request === '') {
            echo "  no explicit animation request; skipped (no LLM call)\n";
            return;
        }

        $tagged = self::taggedElements($project);
        if ($tagged === []) {
            $message = "animation_request present but no '" . self::CLASS_NAME . "' tag in the markup; skipped";
            file_put_contents($project->logPath(self::LOG_FILE), $message . "\nREQUEST: {$request}\n");
            echo "  custom-motion: {$message} (no LLM call)\n";
            // The user explicitly asked for this animation and the site ships
            // without it — that's a delivered defect, not just a log line.
            $project->addWarnings($this->id(), [
                "user-requested animation \"{$request}\" not implemented: no section tagged a '"
                    . self::CLASS_NAME . "' target — see logs/" . self::LOG_FILE,
            ]);
            return;
        }
        $shapeTagged = self::hasShapeTaggedElement($project);

        $rendered = $this->renderer->render('custom-motion.md', [
            'animation_request' => $request,
            'design_direction'  => DesignDirectionStep::readFor($project),
            'tagged_elements'   => implode("\n", $tagged),
        ]);
        $css = CodeFences::strip(
            $this->llm->complete($rendered, $this->withOptions(['log_label' => $this->id()]))
        );

        // Corner language and the committed motion profile are closed
        // build-owned commitments. Keep the requested animation whenever
        // possible by removing only those declarations, including inside
        // keyframes, before applying the rest of the CSS policy below.
        [$css, $droppedShapeDeclarations] = self::dropShapeOwnedDeclarations($css, $shapeTagged);
        [$css, $droppedMotionDeclarations] = self::dropProfileOwnedMotionDeclarations($css);
        foreach (
            [
                'shape-owned corner' => $droppedShapeDeclarations,
                'profile-owned motion custom property' => $droppedMotionDeclarations,
            ] as $kind => $dropped
        ) {
            if ($dropped === []) {
                continue;
            }
            $project->addWarnings($this->id(), array_map(
                static fn (string $declaration): string =>
                    "file='theme/style.css'; block='generated custom-motion CSS'; authored="
                    . Warnings::value($declaration)
                    . "; delivered=removed; disposition=dropped a {$kind} declaration "
                    . 'before validating and appending the remaining motion CSS — see logs/' . self::LOG_FILE,
                $dropped,
            ));
        }
        $problems = self::validate($css, $shapeTagged);
        $preValidationDropLog = implode('', [
            $droppedShapeDeclarations === []
                ? ''
                : "\nSHAPE-OWNED DECLARATIONS REMOVED BEFORE VALIDATION:\n- "
                    . implode("\n- ", $droppedShapeDeclarations) . "\n",
            $droppedMotionDeclarations === []
                ? ''
                : "\nPROFILE-OWNED MOTION DECLARATIONS REMOVED BEFORE VALIDATION:\n- "
                    . implode("\n- ", $droppedMotionDeclarations) . "\n",
        ]);
        if ($problems !== []) {
            file_put_contents(
                $project->logPath(self::LOG_FILE),
                "REJECTED CSS:\n{$css}\n"
                . $preValidationDropLog
                . "\nPROBLEMS:\n- " . implode("\n- ", $problems) . "\n"
            );
            echo '  custom-motion: CSS rejected (' . count($problems)
                . ' problem(s)); skipped — see logs/' . self::LOG_FILE . "\n";
            $project->addWarnings($this->id(), [sprintf(
                'user-requested animation "%s" not implemented: model CSS rejected (%s) — see logs/%s',
                $request,
                implode('; ', $problems),
                self::LOG_FILE,
            )]);
            return;
        }

        $droppedCount = count($droppedShapeDeclarations) + count($droppedMotionDeclarations);
        if ($droppedCount > 0) {
            file_put_contents(
                $project->logPath(self::LOG_FILE),
                "SALVAGED CSS (profile-owned declarations removed):\n{$css}\n"
                . $preValidationDropLog
            );
            echo "  custom-motion: dropped {$droppedCount} profile-owned declaration(s), "
                . 'kept the remaining motion — see logs/' . self::LOG_FILE . "\n";
        }

        // The reduced-motion wrapper is added HERE, deterministically, so a
        // model that forgets it can't ship motion to users who opted out.
        $project->writeText(
            'theme/style.css',
            rtrim($project->readText('theme/style.css'))
            . "\n\n" . self::MARKER
            . "\n@media screen and (prefers-reduced-motion: no-preference) {\n" . $css . "\n}\n"
        );
        echo "  custom-motion: implemented \"{$request}\"\n";
    }

    /**
     * The tagged elements as they appear in the final markup — enough context
     * (tag name, classes) for the model to know what it is animating. For
     * blocks with saved HTML that is the opening tag carrying the class; for
     * dynamic blocks (wp:site-logo, wp:site-title — no saved HTML at all) it
     * is the opening block comment whose "className" carries it. Empty when
     * no step ever placed the class.
     *
     * @return string[]
     */
    public static function taggedElements(Project $project): array
    {
        $found = [];
        $token = '(?<![\w-])' . self::CLASS_NAME . '(?![\w-])';
        foreach ($project->themeFiles() as $rel) {
            $doc = BlockMarkup::parse($project->readText('theme/' . $rel));
            foreach ($doc->indices() as $i) {
                if (preg_match_all('/<[a-z][^>]*class="[^"]*' . $token . '[^"]*"[^>]*>/i', $doc->ownHtml($i), $m) > 0) {
                    foreach ($m[0] as $tag) {
                        $found[] = self::clip($tag);
                    }
                    continue;
                }
                $attrs = $doc->attrs($i);
                $className = is_array($attrs) && is_string($attrs['className'] ?? null) ? $attrs['className'] : '';
                if (preg_match('/' . $token . '/', $className) === 1) {
                    $found[] = self::clip($doc->openingComment($i));
                }
            }
        }
        return array_slice($found, 0, 10);
    }

    /** Whether the custom-motion class is attached to an owned image/button block. */
    public static function hasShapeTaggedElement(Project $project): bool
    {
        $token = '(?<![\w-])' . self::CLASS_NAME . '(?![\w-])';
        foreach ($project->themeFiles() as $rel) {
            $doc = BlockMarkup::parse($project->readText('theme/' . $rel));
            foreach ($doc->indices() as $i) {
                $name = $doc->name($i);
                $name = str_contains($name, '/') ? $name : 'core/' . $name;
                if (!in_array($name, ['core/image', 'core/button'], true)) {
                    continue;
                }
                $attrs = $doc->attrs($i);
                $className = is_array($attrs) && is_string($attrs['className'] ?? null)
                    ? $attrs['className']
                    : '';
                if (preg_match('/' . $token . '/', $className) === 1
                    || preg_match('/\bclass\s*=\s*(["\'])[^"\']*' . $token . '[^"\']*\1/i', $doc->ownHtml($i)) === 1
                ) {
                    return true;
                }
            }
        }
        return false;
    }

    private static function clip(string $element): string
    {
        return strlen($element) > 300 ? substr($element, 0, 300) . '…' : $element;
    }

    /**
     * The relaxed validation ruleset for user-requested animation CSS.
     * Returns problem strings; empty = valid. Pure — unit-testable.
     *
     * @return string[]
     */
    public static function validate(string $css, bool $shapeTagged = false): array
    {
        $css = trim($css);
        if ($css === '') {
            return ['empty CSS'];
        }

        $problems = [];
        if (substr_count($css, "\n") + 1 > self::MAX_LINES) {
            $problems[] = 'more than ' . self::MAX_LINES . ' lines';
        }

        $stripped = (string) preg_replace('~/\*.*?\*/~s', '', $css);
        // A stray `}` here would close the deterministic reduced-motion
        // wrapper this CSS gets concatenated into, letting the rest of the
        // block escape it.
        if (!CssChecks::braceDepthBalanced($stripped)) {
            $problems[] = 'unbalanced braces';
            return $problems; // the structural walks below need balanced braces
        }

        $resource = CssChecks::resourceLoadingProblem($stripped);
        if ($resource !== null) {
            $problems[] = $resource;
        }
        foreach (CssChecks::scanDeclarations($stripped) as $declaration) {
            if (str_starts_with(strtolower($declaration['property']), '--motion-')) {
                $problems[] = 'motion custom properties are profile-owned and cannot be overridden: '
                    . trim($declaration['raw']);
            }
        }
        foreach (CssChecks::hiddenContentProblems($stripped) as $problem) {
            $problems[] = $problem;
        }
        foreach (CssChecks::disallowedAtRules($stripped, ['media', 'keyframes']) as $problem) {
            $problems[] = $problem;
        }
        foreach (self::shapeOwnedDeclarations($stripped, $shapeTagged) as $declaration) {
            $problems[] = 'shape-owned image/button corner declaration is not allowed: '
                . trim($declaration['raw']);
        }

        [$keyframeNames, $rules, $keyframeBodies] = self::stripKeyframes($stripped);
        foreach ($keyframeNames as $name) {
            if (!str_starts_with($name, self::CLASS_NAME . '-')) {
                $problems[] = "keyframe name must start with '" . self::CLASS_NAME . "-': {$name}";
            }
        }

        // Outside keyframes an element must be visible at rest. Parse the
        // value instead of pattern-matching literal zeros: 0%, .0 and calc(0)
        // all hide content just as well as 0.
        if (preg_match_all('/(?<![-\w])opacity\s*:\s*([^;{}]+)/i', $rules, $opacities) > 0) {
            foreach ($opacities[1] as $value) {
                if (self::hidesContent($value)) {
                    $problems[] = 'opacity outside @keyframes must be a plain value above zero: ' . trim($value);
                }
            }
        }

        // Inside keyframes, a hidden state is only ever the transient start
        // of an entrance (`from`/`0%`). In any later step it can be the state
        // a forwards/both fill parks the element in — invisible for good.
        // Both properties that can spell it are checked here, because
        // hiddenContentProblems() exempts every keyframe so that an entrance
        // may legally start clipped (BIGR-887).
        foreach ($keyframeBodies as $body) {
            if (preg_match_all('/([^{}]+)\{([^{}]*)\}/', $body, $steps, PREG_SET_ORDER) === 0) {
                continue;
            }
            foreach ($steps as $step) {
                $selectors = array_map('trim', explode(',', strtolower($step[1])));
                if (array_diff($selectors, ['from', '0%']) === []) {
                    continue;
                }
                if (preg_match_all('/(?<![-\w])opacity\s*:\s*([^;{}]+)/i', $step[2], $opacities) > 0) {
                    foreach ($opacities[1] as $value) {
                        if (self::hidesContent($value)) {
                            $problems[] = 'zero opacity in a non-start keyframe can leave content hidden: '
                                . trim($step[1]) . ' { opacity: ' . trim($value) . ' }';
                        }
                    }
                }
                if (preg_match_all('/(?<![-\w])clip-path\s*:\s*([^;{}]+)/i', $step[2], $clips) > 0) {
                    foreach ($clips[1] as $value) {
                        if (CssChecks::hiddenContentProblems('a{clip-path:' . $value . '}') !== []) {
                            $problems[] = 'a fully-clipping clip-path in a non-start keyframe can leave'
                                . ' content hidden: ' . trim($step[1]) . ' { clip-path: ' . trim($value) . ' }';
                        }
                    }
                }
            }
        }

        // Every remaining rule selector must live under the dedicated class.
        $isScoped = static fn (string $selector): bool =>
            preg_match('/^\.' . self::CLASS_NAME . '(?![\w])/', $selector) === 1
            || preg_match('/^\.' . self::CLASS_NAME . '-[\w-]+/', $selector) === 1;
        foreach (CssChecks::unscopedSelectors($rules, $isScoped) as $selector) {
            $problems[] = "selector not scoped under ." . self::CLASS_NAME . ": {$selector}";
        }

        return $problems;
    }

    /**
     * Remove only declarations that can change the committed corner language.
     * Innermost rule bodies cover ordinary style rules and individual keyframe
     * steps, including rules nested under @media. Selectors, at-rules, and all
     * non-radius declarations survive for the normal validator to assess.
     *
     * Comments are stripped only when a repair is needed: braces inside a
     * comment must not confuse the rule-body walk. Generated comments carry no
     * runtime behavior, so this does not lose authored motion semantics.
     *
     * @return array{0:string,1:list<string>} repaired CSS and dropped declarations
     */
    public static function dropShapeOwnedDeclarations(string $css, bool $shapeTagged = false): array
    {
        $owned = self::shapeOwnedDeclarations($css, $shapeTagged);
        $ownedStarts = array_fill_keys(array_column($owned, 'start'), true);
        [$repaired, $dropped] = CssChecks::dropDeclarations(
            $css,
            static fn (array $declaration): bool => isset($ownedStarts[$declaration['start']]),
        );
        return [
            $repaired,
            array_map(static fn (array $declaration): string => trim($declaration['raw']), $dropped),
        ];
    }

    /**
     * Remove only `--motion-*` custom properties. The committed profile owns
     * those values on `:root`; a local override retunes the element and
     * everything under it. Selectors, at-rules, and every other declaration
     * survive for the normal validator to assess.
     *
     * @return array{0:string,1:list<string>} repaired CSS and dropped declarations
     */
    public static function dropProfileOwnedMotionDeclarations(string $css): array
    {
        [$repaired, $dropped] = CssChecks::dropDeclarations(
            $css,
            static fn (array $declaration): bool =>
                str_starts_with(strtolower($declaration['property']), '--motion-'),
        );
        return [
            $repaired,
            array_map(static fn (array $declaration): string => trim($declaration['raw']), $dropped),
        ];
    }

    /**
     * @return list<array{property:string,value:string,raw:string,start:int,end:int,
     *     context:string,ancestors:list<string>,kind:string}>
     */
    private static function shapeOwnedDeclarations(string $css, bool $shapeTagged): array
    {
        return CssChecks::shapeAffectingDeclarations(
            $css,
            static fn (string $selector): bool => CssChecks::selectorTargetsShape($selector)
                || ($shapeTagged && self::selectorTargetsCustomMotionRoot($selector)),
        );
    }

    private static function selectorTargetsCustomMotionRoot(string $selector): bool
    {
        return CssChecks::selectorTargetsSubject($selector, '.' . self::CLASS_NAME);
    }

    /**
     * Remove @keyframes blocks (brace-aware — they nest) and collect their
     * names and bodies, returning [names, css-without-keyframes, bodies].
     * Pure — unit-testable.
     *
     * @return array{0: string[], 1: string, 2: string[]}
     */
    public static function stripKeyframes(string $css): array
    {
        $names = [];
        $bodies = [];
        $out = '';
        $offset = 0;
        while (preg_match('/@keyframes\s+([\w-]+)\s*\{/i', $css, $m, PREG_OFFSET_CAPTURE, $offset) === 1) {
            $start = $m[0][1];
            $out .= substr($css, $offset, $start - $offset);
            $names[] = $m[1][0];
            $bodyStart = $start + strlen($m[0][0]);
            $i = $bodyStart;
            $depth = 1;
            $length = strlen($css);
            while ($i < $length && $depth > 0) {
                if ($css[$i] === '{') {
                    $depth++;
                } elseif ($css[$i] === '}') {
                    $depth--;
                }
                $i++;
            }
            $bodies[] = substr($css, $bodyStart, max(0, $i - 1 - $bodyStart));
            $offset = $i;
        }
        $out .= substr($css, $offset);
        return [$names, $out, $bodies];
    }

    /**
     * Whether an opacity value hides content: zero in any spelling (0, 0%,
     * .0), or anything that cannot be proven to be a positive plain number
     * (calc(), var(), garbage) — the validator fails closed. Shared with the
     * page-styles validator, which enforces the same visible-at-rest rule.
     */
    public static function hidesContent(string $value): bool
    {
        $value = trim((string) preg_replace('/!important\s*$/i', '', trim($value)));
        if (preg_match('/^(\d*\.?\d+)\s*(%?)$/', $value, $m) !== 1) {
            return true;
        }
        $number = (float) $m[1];
        return ($m[2] === '%' ? $number / 100 : $number) <= 0.0;
    }
}
