<?php
declare(strict_types=1);

namespace Automattic\SiteBuild\Steps;

use Automattic\SiteBuild\BlockMarkup;
use Automattic\SiteBuild\Env;
use Automattic\SiteBuild\Project;
use Automattic\SiteBuild\Step;
use Automattic\SiteBuild\StepDeclaration;

/**
 * Step (deterministic): enforce the header/hero composition contract
 * (BIGR-735) that the sections step injected into the header and hero
 * prompts. The header and every section are generated by independent
 * concurrent LLM calls, so nothing upstream verifies the two sides of the
 * page-top seam actually compose; this step is the deterministic backstop.
 *
 * Input:  pages.json + designDirection.json + siteSpec.json + theme/parts/*
 * Output: the same parts with contract violations repaired, plus
 *         logs/header-hero.txt listing every repair.
 *
 * Four repairs, each observed shipping in every audited project:
 *  1. Overlay wiring — in overlay mode the header's top-level group MUST
 *     carry the `header-overlay` class (the theme CSS shipped unused 6/6
 *     audited builds) and must be transparent and non-sticky; in stacked
 *     mode a stray `header-overlay` class is removed.
 *  2. Fold budget — in stacked mode an opaque header consumes ~100px of the
 *     first viewport, so a page-opening cover taller than 84vh is lowered to
 *     80vh (header + cover must fit ~100vh; audited covers ran 86-92vh and
 *     pushed the hero H1 and CTA below the fold). Only the cover half is
 *     enforced here: the header's own height is asked for in prompts/header.md
 *     and never measured, so the cap assumes a compliant header. A header that
 *     busts its budget still pushes content below the fold, and this step will
 *     not say so — estimating header height the way estimatedRowWidth()
 *     estimates width would be the way to close that.
 *  3. Nav collapse — WordPress's hamburger only engages below 600px, while
 *     an over-wide title/nav row wraps into a 2-3 row header across the
 *     whole tablet range. When the estimated single-row width exceeds the
 *     budget, the navigation gets `"overlayMenu":"always"`.
 *  4. Title scale — a site title at `section-title`/`display` competes with
 *     the hero's display H1 (audited ratios collapsed to 1.33x); it is
 *     rewritten to `heading` unless the build forced the oversized-wordmark
 *     archetype, whose whole point is a display-scale wordmark.
 *
 * Runs BEFORE fix-blocks on purpose (same rationale as contrast-fix and
 * motion-sanity): repairs rewrite only the block-comment JSON attributes,
 * and the fix-blocks re-serialization regenerates the saved HTML from those
 * attributes. Class tokens obsoleted in the saved HTML are removed here too,
 * so the fixer's fixCustomClassname cannot resurrect them.
 */
final class HeaderHeroStep implements Step
{
    private const REPORT_FILE = 'header-hero.txt';

    private const OVERLAY_CLASS = 'header-overlay';

    /** A stacked-mode page-opening cover above this many vh is lowered… */
    public const MAX_STACKED_COVER_VH = 84;

    /** …to this height, so header + cover fit one ~100vh viewport. */
    public const STACKED_COVER_VH = 80;

    /**
     * The single-row width the header must fit (a ~1024px viewport minus
     * gutters). Above it the nav collapses to a menu instead of wrapping.
     */
    public const ROW_BUDGET_PX = 1000;

    /**
     * Rough per-element widths for the row estimate, in px. Deliberately
     * coarse: uppercase caption nav labels track wide (~11px/char at 14px +
     * 0.14em letter-spacing), a heading-size wordmark runs ~17px/char, and a
     * caption button label ~9px/char inside ~56px of padding. The estimate
     * only has to separate "fits comfortably" from "wraps on tablets".
     */
    private const NAV_CHAR_PX = 11;
    private const NAV_GAP_PX = 28;
    private const TITLE_CHAR_PX = 17;
    private const BUTTON_CHAR_PX = 9;
    private const BUTTON_PAD_PX = 56;
    private const LOGO_GAP_PX = 16;
    private const CLUSTER_GAP_PX = 32;
    private const GUTTERS_PX = 64;

    public function id(): string
    {
        return 'header-hero';
    }

    public function label(): string
    {
        return 'Header/hero composition pass';
    }

    public function declaration(): StepDeclaration
    {
        return new StepDeclaration(
            id: $this->id(),
            label: $this->label(),
            reads: ['pages.json', 'designDirection.json', 'siteSpec.json', 'theme/parts/*'],
            writes: ['theme/parts/*', 'warnings.json'],
            concurrent: false,
        );
    }

    public function run(Project $project): void
    {
        if (!$project->exists('theme/parts/header.html') || !$project->exists('pages.json')) {
            return;
        }
        $pages = array_values(array_filter(
            (array) ($project->readJson('pages.json')['pages'] ?? []),
            'is_array',
        ));
        if ($pages === []) {
            return;
        }
        $mode = self::expectedMode($pages, DesignDirectionStep::canvasFor($project));
        $siteName = $project->exists('siteSpec.json')
            ? (string) ($project->readJson('siteSpec.json')['name'] ?? '')
            : '';
        $pageTitles = array_map(static fn (array $p): string => (string) ($p['title'] ?? ''), $pages);

        $report = [];
        $headerRel = 'parts/header.html';
        $header = $project->readText('theme/' . $headerRel);
        $result = self::fixHeader(
            $header,
            $mode,
            $siteName,
            $pageTitles,
            Env::get(SectionsStep::ARCHETYPE_ENV) === 'oversized-wordmark',
        );
        if ($result['markup'] !== $header) {
            $project->writeText('theme/' . $headerRel, $result['markup']);
        }
        foreach ($result['notes'] as $note) {
            $report[] = "[{$headerRel}] {$note}";
        }

        if ($mode === SectionsStep::MODE_STACKED) {
            foreach ($pages as $page) {
                $pageSlug = trim((string) ($page['slug'] ?? ''));
                $slug = trim((string) (SectionsStep::openingSection($page)['slug'] ?? ''));
                if ($pageSlug === '' || $slug === '') {
                    continue;
                }
                $rel = 'parts/' . SectionsStep::partSlug($pageSlug, $slug) . '.html';
                if (!$project->exists('theme/' . $rel)) {
                    continue;
                }
                $markup = $project->readText('theme/' . $rel);
                $result = self::capCovers($markup);
                if ($result['markup'] !== $markup) {
                    $project->writeText('theme/' . $rel, $result['markup']);
                }
                foreach ($result['notes'] as $note) {
                    $report[] = "[{$rel}] {$note}";
                }
            }
        }

        // Each repair changed an authored value the build shipped through —
        // deliberate contract enforcement, recorded durably for the later
        // repair pass, same as the motion budget strips.
        $project->addWarnings($this->id(), array_map(
            static fn (string $row): string => "header/hero contract: {$row}",
            $report,
        ));
        if ($report === []) {
            $report[] = "Header mode '{$mode}': header and page-opening sections already satisfy the "
                . 'repairs this step makes. Header height is prompt-enforced only and was not measured.';
        }
        $project->writeText('logs/' . self::REPORT_FILE, implode("\n", $report) . "\n");
        echo sprintf("  header/hero: mode '%s' (details: logs/%s)\n", $mode, self::REPORT_FILE);
    }

    /**
     * The header mode this build committed to. A forced HEADER_ARCHETYPE env
     * override wins (a forced minimal-overlay is overlay mode, any other
     * forced archetype is stacked); otherwise the same pure decision the
     * sections step injected into the prompts.
     *
     * @param array<int,array<string,mixed>> $pages
     */
    public static function expectedMode(array $pages, string $canvas): string
    {
        $forced = Env::get(SectionsStep::ARCHETYPE_ENV);
        if ($forced !== null && $forced !== '') {
            // SectionsStep::headerAssignment() throws on an unrecognized value,
            // per the policy that a misconfigured environment override is our
            // bug rather than the model's. Validate identically here: this step
            // can run in its own process on a resumed build, where nothing else
            // has looked at the variable yet, and silently reading a typo as
            // "stacked" would enforce the opposite seam the operator asked for.
            if (!in_array($forced, SectionsStep::HEADER_ARCHETYPES, true)) {
                throw new \RuntimeException(sprintf(
                    'header-hero: %s=%s is not a header archetype (use one of: %s)',
                    SectionsStep::ARCHETYPE_ENV,
                    $forced,
                    implode(', ', SectionsStep::HEADER_ARCHETYPES),
                ));
            }
            return $forced === 'minimal-overlay'
                ? SectionsStep::MODE_OVERLAY
                : SectionsStep::MODE_STACKED;
        }
        return SectionsStep::headerMode($pages, $canvas);
    }

    /**
     * Repair the header part against the contract. Pure — unit-testable.
     *
     * @param list<string> $pageTitles page-list nav labels (a wp:page-list
     *                                 renders one item per site page)
     * @return array{markup:string, notes:string[]}
     */
    public static function fixHeader(
        string $markup,
        string $mode,
        string $siteName,
        array $pageTitles = [],
        bool $oversizedForced = false,
    ): array {
        $doc = BlockMarkup::parse($markup);
        $notes = [];

        $top = $doc->topLevel();
        if ($top !== null && $mode === SectionsStep::MODE_OVERLAY) {
            self::wireOverlay($doc, $top, $notes);
        } elseif ($top !== null) {
            self::stripOverlay($doc, $top, $notes);
        }

        foreach ($doc->indices() as $i) {
            if ($doc->name($i) !== 'site-title' || $oversizedForced) {
                continue;
            }
            $attrs = $doc->attrs($i) ?? [];
            $size = (string) ($attrs['fontSize'] ?? '');
            if (in_array($size, ['section-title', 'display'], true)) {
                $attrs['fontSize'] = 'heading';
                $doc->setAttrs($i, $attrs);
                $doc->replaceInOwnHtml($i, "has-{$size}-font-size", 'has-heading-font-size');
                $notes[] = "site-title fontSize '{$size}' lowered to 'heading' "
                    . "(a wordmark at section scale competes with the hero's display headline)";
            }
        }

        $width = self::estimatedRowWidth($doc, $siteName, $pageTitles);
        if ($width > self::ROW_BUDGET_PX) {
            foreach ($doc->indices() as $i) {
                if ($doc->name($i) !== 'navigation') {
                    continue;
                }
                $attrs = $doc->attrs($i) ?? [];
                if (($attrs['overlayMenu'] ?? '') !== 'always') {
                    $attrs['overlayMenu'] = 'always';
                    $doc->setAttrs($i, $attrs);
                    $notes[] = "navigation set to overlayMenu:always (estimated row width ~{$width}px "
                        . 'exceeds the ' . self::ROW_BUDGET_PX . 'px budget; the core hamburger only '
                        . 'engages below 600px, so an over-wide row wraps across the whole tablet range)';
                }
                break;
            }
        }

        return ['markup' => $doc->render(), 'notes' => $notes];
    }

    /**
     * Overlay mode: the top-level group must carry the `header-overlay` class
     * hook (the shipped `.header-overlay` CSS does the floating) and must be
     * transparent and non-sticky — an opaque or sticky overlay defeats it.
     */
    private static function wireOverlay(BlockMarkup $doc, int $top, array &$notes): void
    {
        $attrs = $doc->attrs($top) ?? [];
        $tokens = preg_split('/\s+/', trim((string) ($attrs['className'] ?? '')), -1, PREG_SPLIT_NO_EMPTY) ?: [];
        $changed = [];
        if (!in_array(self::OVERLAY_CLASS, $tokens, true)) {
            $tokens[] = self::OVERLAY_CLASS;
            $attrs['className'] = implode(' ', $tokens);
            $changed[] = "added the '" . self::OVERLAY_CLASS . "' class hook";
        }
        $background = (string) ($attrs['backgroundColor'] ?? '');
        if ($background !== '') {
            unset($attrs['backgroundColor']);
            $doc->removeClassTokenInOwnHtml($top, 'has-background');
            $doc->removeClassTokenInOwnHtml($top, "has-{$background}-background-color");
            $changed[] = "removed the opaque '{$background}' background";
        }
        $gradient = (string) ($attrs['gradient'] ?? '');
        if ($gradient !== '') {
            unset($attrs['gradient']);
            $doc->removeClassTokenInOwnHtml($top, 'has-background');
            $doc->removeClassTokenInOwnHtml($top, "has-{$gradient}-gradient-background");
            $changed[] = "removed the '{$gradient}' gradient background";
        }
        if (isset($attrs['style']['color'])) {
            unset($attrs['style']['color']);
            $doc->removeClassTokenInOwnHtml($top, 'has-background');
            $changed[] = 'removed the custom background color';
        }
        if (isset($attrs['style']['position'])) {
            unset($attrs['style']['position']);
            $changed[] = 'removed the sticky position';
        }
        if (isset($attrs['style']) && $attrs['style'] === []) {
            unset($attrs['style']);
        }
        if ($changed !== []) {
            $doc->setAttrs($top, $attrs);
            $notes[] = 'overlay header wiring: ' . implode(', ', $changed)
                . ' (overlay mode floats the header transparently over the hero cover)';
        }
    }

    /**
     * Stacked mode: a stray `header-overlay` class would float the header
     * over content that never reserved space for it — remove the hook.
     */
    private static function stripOverlay(BlockMarkup $doc, int $top, array &$notes): void
    {
        $attrs = $doc->attrs($top) ?? [];
        $tokens = preg_split('/\s+/', trim((string) ($attrs['className'] ?? '')), -1, PREG_SPLIT_NO_EMPTY) ?: [];
        if (!in_array(self::OVERLAY_CLASS, $tokens, true)) {
            return;
        }
        $kept = array_values(array_diff($tokens, [self::OVERLAY_CLASS]));
        if ($kept === []) {
            unset($attrs['className']);
        } else {
            $attrs['className'] = implode(' ', $kept);
        }
        $doc->setAttrs($top, $attrs);
        $doc->removeClassTokenInOwnHtml($top, self::OVERLAY_CLASS);
        $notes[] = "removed the '" . self::OVERLAY_CLASS . "' class "
            . '(stacked mode: the hero composed for an opaque bar above it, not a floating header)';
    }

    /**
     * Lower page-opening covers that cannot share a ~100vh viewport with a
     * stacked header. Pure — unit-testable.
     *
     * @return array{markup:string, notes:string[]}
     */
    public static function capCovers(string $markup): array
    {
        $doc = BlockMarkup::parse($markup);
        $notes = [];
        foreach ($doc->indices() as $i) {
            if ($doc->name($i) !== 'cover') {
                continue;
            }
            $attrs = $doc->attrs($i) ?? [];
            $height = $attrs['minHeight'] ?? null;
            if (!is_numeric($height)
                || (string) ($attrs['minHeightUnit'] ?? '') !== 'vh'
                || (float) $height <= self::MAX_STACKED_COVER_VH) {
                continue;
            }
            // Attribute-only edit: the stale inline min-height style survives
            // until fix-blocks re-serializes the saved HTML from these attrs.
            $attrs['minHeight'] = self::STACKED_COVER_VH;
            $doc->setAttrs($i, $attrs);
            $notes[] = "cover minHeight {$height}vh lowered to " . self::STACKED_COVER_VH . 'vh '
                . '(an opaque header stacks above this page-opening section; together they must fit one viewport)';
        }
        return ['markup' => $doc->render(), 'notes' => $notes];
    }

    /**
     * Rough single-row width of the header bar at desktop: wordmark cluster +
     * navigation labels + button labels + gaps. Hand-authored
     * wp:navigation-link labels are read from the markup; a wp:page-list
     * renders one item per site page, so page titles stand in for its labels.
     * Pure — unit-testable.
     *
     * @param list<string> $pageTitles
     */
    public static function estimatedRowWidth(BlockMarkup $doc, string $siteName, array $pageTitles = []): int
    {
        $width = self::GUTTERS_PX;
        $labels = [];
        $hasPageList = false;
        $hasTitle = false;
        $hasButton = false;

        foreach ($doc->indices() as $i) {
            $name = $doc->name($i);
            if ($name === 'navigation-link') {
                $labels[] = (string) (($doc->attrs($i) ?? [])['label'] ?? '');
            } elseif ($name === 'page-list') {
                $hasPageList = true;
            } elseif ($name === 'site-title') {
                $hasTitle = true;
            } elseif ($name === 'site-logo') {
                $width += (int) (($doc->attrs($i) ?? [])['width'] ?? 48) + self::LOGO_GAP_PX;
            } elseif ($name === 'button') {
                $label = trim(strip_tags($doc->innerHtml($i)));
                $width += self::BUTTON_PAD_PX + mb_strlen($label) * self::BUTTON_CHAR_PX;
                $hasButton = true;
            }
        }
        if ($hasPageList) {
            $labels = array_merge($labels, $pageTitles);
        }
        if ($hasTitle) {
            $width += mb_strlen($siteName) * self::TITLE_CHAR_PX + self::CLUSTER_GAP_PX;
        }
        foreach ($labels as $label) {
            $width += mb_strlen(trim($label)) * self::NAV_CHAR_PX + self::NAV_GAP_PX;
        }
        if ($hasButton) {
            $width += self::CLUSTER_GAP_PX;
        }
        return $width;
    }
}
