<?php
declare(strict_types=1);

namespace Automattic\SiteBuild\Steps;

use Automattic\SiteBuild\BlockMarkup;
use Automattic\SiteBuild\Device;
use Automattic\SiteBuild\Motion;
use Automattic\SiteBuild\Project;
use Automattic\SiteBuild\Step;
use Automattic\SiteBuild\StepDeclaration;

/**
 * Step (deterministic): enforce the motion-class budget across every rendered
 * page (each page in pages.json gets its own page-level budgets; the chrome
 * shares the front page's).
 *
 * Input:  designDirection.json (the committed motion profile) + pages.json +
 *         theme/parts/*.html + theme/templates/*.html
 * Output: the same files with over-budget motion classes removed, plus
 *         logs/motion-sanity.txt listing every removal.
 *
 * Sections are generated by independent concurrent LLM calls, so nothing
 * upstream enforces site-level motion coherence — one section could take
 * three effects while four take none, or every section could claim the one
 * ambient "signature" slot. The section prompt states the budget; this step
 * is the deterministic backstop. It only ever REMOVES class tokens, never
 * adds them:
 *  - unknown motion-flavored classes (invented `reveal-left` variants and the
 *    JS-owned `is-visible` state class) — they have no CSS, or fight the kit;
 *  - classes the committed motion profile disallows (`minimal` keeps hover
 *    effects only; `none` strips every motion class);
 *  - `hero-entrance` outside the first planned section or beyond the FIRST
 *    one on the page;
 *  - scroll/page-load entrances beyond two in a section, so a long repeated
 *    list cannot animate every row with the same recipe;
 *  - same-block ambient/hover pairs whose animations compete for transform;
 *  - extra kit classes beyond the first on a single block, and
 *    `stagger-children` on containers without at least two child blocks.
 *
 * Runs BEFORE fix-blocks on purpose (same rationale as contrast-fix): edits
 * rewrite only the block-comment JSON attributes, and the fix-blocks
 * re-serialization regenerates the saved HTML from those attributes. Because
 * the fixer's fixCustomClassname rescues classes that live only in the saved
 * HTML into className, the saved HTML is part of the gate: motion classes
 * found there are judged exactly like comment-JSON ones, and every stripped
 * token is removed from the block's own class="…" HTML (tokenized, so odd
 * whitespace can't shelter one) so the fixer can't resurrect it.
 *
 * HTML-first composition mode skips the legacy motion pass but still runs the
 * device budget: that graph ships the device CSS and its prompts promise the
 * build strips an over-budget or hero-placed device. Mode is injected by
 * StepComposition; stale design artifacts never choose behavior.
 */
final class MotionSanityStep implements Step
{
    private const REPORT_FILE = 'motion-sanity.txt';

    public function __construct(private bool $htmlFirst = false) {}

    public function id(): string
    {
        return 'motion-sanity';
    }

    public function label(): string
    {
        return 'Motion sanity pass';
    }

    public function declaration(): StepDeclaration
    {
        return new StepDeclaration(
            id: $this->id(),
            label: $this->label(),
            // Templates are only scanned when they exist; in the default graph
            // they are written by assemble-pages, which runs after this step.
            reads: ['designDirection.json', 'pages.json', 'theme/parts/*'],
            writes: ['theme/parts/*', 'warnings.json'],
            concurrent: false,
        );
    }

    public function run(Project $project): void
    {
        // The html-first path skips the legacy motion fixup, but the device
        // budget is not motion work: prompts/homepage-design.md and
        // prompts/inner-section-design.md both tell the model the build strips
        // a device off the hero or off a second band, and FinalizeThemeStep
        // ships the device CSS in that graph too. Transform keeps authored
        // classes (BlockFactory), so the guard still has markup to read here.
        if ($this->htmlFirst) {
            $project->addWarnings('fixup_skipped', [
                'step=motion-sanity; signal=composition-mode:html-first; disposition=skipped; '
                    . 'reason=new CSS path does not use legacy motion fixup',
            ]);
        }

        $profile = DesignDirectionStep::motionProfileFor($project);
        $deviceClass = Device::className(DesignDirectionStep::deviceFor($project));
        $report = [];

        foreach (self::fileGroups($project) as $group) {
            $budget = self::newBudget();
            foreach ($group['files'] as $rel) {
                $markup = $project->readText('theme/' . $rel);
                $result = self::sanitize(
                    $markup,
                    $profile,
                    $budget,
                    $rel === $group['hero'],
                    $deviceClass,
                    $this->htmlFirst,
                );
                if ($result['markup'] !== $markup) {
                    $project->writeText('theme/' . $rel, $result['markup']);
                }
                foreach ($result['notes'] as $note) {
                    $report[] = "[{$rel}] {$note}";
                }
            }
        }

        // Each strip removed an authored class from the delivered markup —
        // deliberate policy enforcement, but still a change the build shipped
        // through; record it durably for the later repair pass. Device drops
        // are named as such: every device note quotes its `device--` token,
        // and no motion note ever carries that prefix.
        $isDeviceNote = static fn (string $row): bool => str_contains($row, Device::CLASS_PREFIX);
        $project->addWarnings($this->id(), array_map(
            static fn (string $row): string => $isDeviceNote($row)
                ? "device class stripped: {$row}"
                : "motion class stripped: {$row}",
            $report,
        ));

        $devices = count(array_filter($report, $isDeviceNote));
        $motions = count($report) - $devices;

        // In html-first only the device guard ran, so staying silent when it
        // found nothing keeps the step's skip contract intact.
        if ($this->htmlFirst) {
            if ($report !== []) {
                $project->writeText('logs/' . self::REPORT_FILE, implode("\n", $report) . "\n");
            }
            echo sprintf("  device: %d class(es) stripped\n", $devices);
            return;
        }

        if ($report === []) {
            $report[] = "Motion profile '{$profile}': all motion and device classes within budget.";
        }
        $project->writeText('logs/' . self::REPORT_FILE, implode("\n", $report) . "\n");

        echo sprintf(
            "  motion: profile '%s', %d motion + %d device class(es) stripped (details: logs/%s)\n",
            $profile, $motions, $devices, self::REPORT_FILE
        );
    }

    /**
     * Fresh page-level budget state, threaded through sanitize() calls so the
     * one-per-page limits span every file of the page.
     *
     * @return array{ambient:int, hero:int, device:int}
     */
    public static function newBudget(): array
    {
        return ['ambient' => 0, 'hero' => 0, 'device' => 0];
    }

    /**
     * Theme files grouped per rendered page, so the page-level budgets
     * (one ambient signature, one hero-entrance) apply to each page of a
     * multi-page site independently. Within a group the page's section parts
     * come first in plan order (the "first ambient wins" budget should favor
     * the hero, not whichever filename globs first); the chrome parts,
     * templates, and any unplanned files join the FRONT page's group — the
     * site's centerpiece, and the page whose first section the header sits
     * on. Each group's 'hero' is the one file allowed to carry
     * hero-entrance: the page's first planned section part (a hero's slug
     * need not literally be "hero"), the conventional filename for plan-less
     * projects.
     *
     * @return list<array{files:string[], hero:?string}>
     */
    public static function fileGroups(Project $project): array
    {
        $all = $project->themeFiles();

        $pages = $project->exists('pages.json')
            ? (array) ($project->readJson('pages.json')['pages'] ?? [])
            : [];
        $pages = array_values(array_filter($pages, 'is_array'));
        if ($pages === []) {
            $conventional = 'parts/' . SectionsStep::PART_PREFIX . 'hero.html';
            return [[
                'files' => $all,
                'hero'  => in_array($conventional, $all, true) ? $conventional : null,
            ]];
        }

        $groups = [];
        $frontIndex = null;
        $used = [];
        foreach ($pages as $page) {
            $pageSlug = trim((string) ($page['slug'] ?? ''));
            $files = [];
            foreach ((array) ($page['sections'] ?? []) as $section) {
                if (!is_array($section)) {
                    continue;
                }
                $slug = trim((string) ($section['slug'] ?? ''));
                $rel = 'parts/' . SectionsStep::partSlug($pageSlug, $slug) . '.html';
                if ($slug !== '' && in_array($rel, $all, true)) {
                    $files[] = $rel;
                    $used[$rel] = true;
                }
            }
            if ($frontIndex === null && !empty($page['front'])) {
                $frontIndex = count($groups);
            }
            $groups[] = ['files' => $files, 'hero' => $files[0] ?? null];
        }
        $frontIndex ??= 0;

        foreach ($all as $rel) {
            if (!isset($used[$rel])) {
                $groups[$frontIndex]['files'][] = $rel;
            }
        }
        return $groups;
    }

    /**
     * Strip over-budget motion classes from one document. Removal-only: the
     * kept class list is always a subset of the authored one. $budget carries
     * the page-level counters across files. Pure — unit-testable.
     *
     * @param array{ambient:int, hero:int, device:int} $budget
     * @param ?string $deviceClass the one device class the direction committed,
     *        or null when it committed none. prompts/page-plan.md budgets it to
     *        one non-hero band per page, and nothing was checking that after
     *        the model wrote the markup.
     * @param bool $deviceOnly hold the device budget and leave motion classes
     *        untouched — the html-first path ships the device CSS but does not
     *        use the legacy motion fixup.
     * @return array{markup:string, notes:string[]}
     */
    public static function sanitize(
        string $markup,
        string $profile,
        array &$budget,
        bool $heroAllowed = true,
        ?string $deviceClass = null,
        bool $deviceOnly = false,
    ): array
    {
        $doc = BlockMarkup::parse($markup);
        $allowed = Motion::allowedClasses($profile);
        $notes = [];
        $sectionEntrances = 0;

        foreach ($doc->indices() as $i) {
            self::enforceDeviceBudget($doc, $i, $deviceClass, $heroAllowed, $budget, $notes);
            if ($deviceOnly) {
                continue;
            }
            $attrs = $doc->attrs($i) ?? [];
            $className = $attrs['className'] ?? null;
            $jsonTokens = is_string($className)
                ? (preg_split('/\s+/', trim($className), -1, PREG_SPLIT_NO_EMPTY) ?: [])
                : [];

            // Motion classes living only in the saved HTML count too: the
            // block fixer that runs right after this step rescues them into
            // className (fixCustomClassname), so skipping them here would let
            // an HTML-only class ride around the profile gate and budgets.
            $htmlTokens = self::classTokensInOwnHtml($doc, $i);
            $htmlOnly = array_values(array_filter(
                array_diff(array_unique($htmlTokens), $jsonTokens),
                [Motion::class, 'looksLikeMotionClass']
            ));
            if ($jsonTokens === [] && $htmlOnly === []) {
                continue;
            }

            // A block tagged for the custom-motion step is the user's ONE
            // explicit animation request. The kit's higher-specificity static
            // motion selector (html.motion-js
            // .reveal-*.motion-target.is-visible) would override the generated
            // .custom-motion animation, so preset motion is evicted here.
            $customTarget = in_array(CustomMotionStep::CLASS_NAME, $jsonTokens, true)
                || in_array(CustomMotionStep::CLASS_NAME, $htmlTokens, true);

            $droppedJson = [];
            $droppedHtml = [];
            $kitOnBlock = 0;
            $keptKitClass = null;

            // Evaluate transform-owning entrance/ambient classes before hover
            // regardless of authored token order. That lets the hover verdict
            // reject a conflict only when the other class actually survived
            // profile/page/block budgets; if it was stripped, hover still works.
            $entries = [];
            $seenTokens = [];
            foreach ($jsonTokens as $token) {
                // Duplicate class tokens are behaviorally identical. Judge
                // the token once so a redundant second copy cannot cause the
                // valid first copy to be marked as an over-budget drop.
                if (isset($seenTokens[$token])) {
                    continue;
                }
                $seenTokens[$token] = true;
                $entries[] = ['source' => 'json', 'token' => $token];
            }
            foreach ($htmlOnly as $token) {
                if (isset($seenTokens[$token])) {
                    continue;
                }
                $seenTokens[$token] = true;
                $entries[] = ['source' => 'html', 'token' => $token];
            }
            $nonHover = array_values(array_filter(
                $entries,
                static fn (array $entry): bool => !in_array($entry['token'], Motion::HOVER_CLASSES, true)
            ));
            $hover = array_values(array_filter(
                $entries,
                static fn (array $entry): bool => in_array($entry['token'], Motion::HOVER_CLASSES, true)
            ));

            foreach (array_merge($nonHover, $hover) as $entry) {
                $token = $entry['token'];
                $verdict = self::verdict(
                    $token,
                    $allowed,
                    $kitOnBlock,
                    $keptKitClass,
                    $sectionEntrances,
                    $budget,
                    $doc,
                    $i,
                    $heroAllowed,
                    $customTarget
                );
                if ($verdict === null) {
                    continue;
                }
                if ($entry['source'] === 'json') {
                    $droppedJson[] = $token;
                    $notes[] = "{$doc->name($i)}: dropped '{$token}' ({$verdict})";
                } else {
                    $droppedHtml[] = $token;
                    $notes[] = "{$doc->name($i)}: dropped '{$token}' (saved HTML only; {$verdict})";
                }
            }

            if ($droppedJson !== []) {
                $kept = array_values(array_diff($jsonTokens, $droppedJson));
                if ($kept === []) {
                    unset($attrs['className']);
                } else {
                    $attrs['className'] = implode(' ', $kept);
                }
                $doc->setAttrs($i, $attrs);
            }

            // Also remove each token from the block's own class="…" HTML —
            // tokenized, so tab/newline separators can't shelter a token the
            // fixer would then rescue right back into className.
            foreach (array_merge($droppedJson, $droppedHtml) as $token) {
                $doc->removeClassTokenInOwnHtml($i, $token);
            }
        }

        return ['markup' => $doc->render(), 'notes' => $notes];
    }

    /**
     * Hold the one-band device budget the prompt only asked for.
     *
     * prompts/page-plan.md says at most one non-hero band carries the device,
     * and until this ran nothing checked it afterwards — a build could skip the
     * class, use it twice, put it on the hero, or invent a variant with no CSS,
     * and nobody found out. Removal-only, like every other pass here.
     *
     * @param array{ambient:int, hero:int, device:int} $budget
     * @param list<string> $notes
     */
    private static function enforceDeviceBudget(
        BlockMarkup $doc,
        int $i,
        ?string $deviceClass,
        bool $isHero,
        array &$budget,
        array &$notes,
    ): void {
        $attrs = $doc->attrs($i) ?? [];
        $className = $attrs['className'] ?? null;
        $jsonTokens = is_string($className)
            ? (preg_split('/\s+/', trim($className), -1, PREG_SPLIT_NO_EMPTY) ?: [])
            : [];
        $htmlTokens = self::classTokensInOwnHtml($doc, $i);

        $candidates = array_values(array_unique(array_filter(
            array_merge($jsonTokens, $htmlTokens),
            static fn (string $token): bool => str_starts_with($token, Device::CLASS_PREFIX),
        )));
        if ($candidates === []) {
            return;
        }

        $dropped = [];
        foreach ($candidates as $token) {
            $reason = match (true) {
                $deviceClass === null => 'the direction committed no device',
                $token !== $deviceClass => "not the committed device ({$deviceClass})",
                $isHero => 'the hero never carries the device',
                $budget['device'] >= 1 => 'one band per page already carries it',
                default => null,
            };
            if ($reason === null) {
                $budget['device']++;
                continue;
            }
            $dropped[] = $token;
            $notes[] = "{$doc->name($i)}: dropped '{$token}' ({$reason})";
        }
        if ($dropped === []) {
            return;
        }

        $kept = array_values(array_diff($jsonTokens, $dropped));
        if (is_string($className)) {
            if ($kept === []) {
                unset($attrs['className']);
            } else {
                $attrs['className'] = implode(' ', $kept);
            }
            $doc->setAttrs($i, $attrs);
        }
        foreach ($dropped as $token) {
            $doc->removeClassTokenInOwnHtml($i, $token);
        }
    }

    /**
     * Every class token in the block's own saved HTML (its root tag; both
     * quote styles, any whitespace separators).
     *
     * @return string[]
     */
    private static function classTokensInOwnHtml(BlockMarkup $doc, int $i): array
    {
        if (preg_match_all('/\bclass\s*=\s*(["\'])(.*?)\1/is', $doc->ownHtml($i), $m) === 0) {
            return [];
        }
        $tokens = [];
        foreach ($m[2] as $value) {
            foreach (preg_split('/\s+/', $value, -1, PREG_SPLIT_NO_EMPTY) ?: [] as $token) {
                $tokens[] = $token;
            }
        }
        return $tokens;
    }

    /**
     * Why one class token must be dropped, or null to keep it. Mutates the
     * per-block kit counter and the page-level budget when a budgeted class
     * is KEPT.
     *
     * @param string[] $allowed
     * @param array{ambient:int, hero:int} $budget
     */
    private static function verdict(
        string $token,
        array $allowed,
        int &$kitOnBlock,
        ?string &$keptKitClass,
        int &$sectionEntrances,
        array &$budget,
        BlockMarkup $doc,
        int $i,
        bool $heroAllowed = true,
        bool $customTarget = false,
    ): ?string {
        if (!Motion::looksLikeMotionClass($token)) {
            return null; // not a motion class — none of our business
        }
        if ($token === Motion::STATE_CLASS) {
            return 'JS-owned state class; never authored';
        }

        $isKit = in_array($token, Motion::kitClasses(), true);
        $isHover = in_array($token, Motion::HOVER_CLASSES, true);
        if (!$isKit && !$isHover) {
            return 'unknown motion class — no CSS ships for it';
        }
        if ($customTarget) {
            return 'the block is the custom-motion target — preset motion would override the explicit request';
        }
        if (!in_array($token, $allowed, true)) {
            return "disallowed by the motion profile";
        }
        if ($isHover) {
            $conflict = match ($token) {
                'hover-lift'   => 'ambient-drift',
                'hover-reveal' => 'ken-burns',
                default        => null,
            };
            if ($conflict !== null
                && $keptKitClass === $conflict) {
                return "incompatible with '{$conflict}' on the same block — both animate the same transform";
            }
            return null; // hover effects don't count toward any budget
        }

        if ($kitOnBlock >= 1) {
            return 'a block gets at most one motion class';
        }
        if ($token === 'stagger-children' && count($doc->children($i)) < 2) {
            return 'stagger-children needs a container with at least two children';
        }
        $isEntrance = in_array($token, Motion::SCROLL_CLASSES, true);
        $isAmbient = in_array($token, Motion::AMBIENT_CLASSES, true);
        $isHero = in_array($token, Motion::HERO_CLASSES, true);
        // hero-entrance and word-reveal budget separately: the copy group
        // may fade in while the headline's words arrive one at a time.
        $heroKey = $token === 'hero-entrance' ? 'hero' : 'word';
        $budget[$heroKey] ??= 0;

        // Check every budget before consuming any of them: a class rejected
        // by a page-level limit must not steal this section's entrance slot.
        if ($isHero && !$heroAllowed) {
            return "{$token} is allowed only in the first section";
        }
        if ($isEntrance && $sectionEntrances >= Motion::MAX_ENTRANCES_PER_SECTION) {
            return 'section entrance budget: at most two entrances per section';
        }
        if ($isAmbient && $budget['ambient'] >= 1) {
            return 'ambient budget: one signature effect per page';
        }
        if ($isHero && $budget[$heroKey] >= 1) {
            return "{$token} budget: once per page";
        }

        if ($isEntrance) {
            $sectionEntrances++;
        }
        if ($isAmbient) {
            $budget['ambient']++;
        }
        if ($isHero) {
            $budget[$heroKey]++;
        }

        $keptKitClass = $token;
        $kitOnBlock++;
        return null;
    }
}
