<?php
declare(strict_types=1);

namespace Automattic\SiteBuild\Steps;

use Automattic\SiteBuild\BlockMarkup;
use Automattic\SiteBuild\Motion;
use Automattic\SiteBuild\Project;
use Automattic\SiteBuild\Step;

/**
 * Step (deterministic): enforce the motion-class budget across the whole page.
 *
 * Input:  designDirection.json (the committed motion profile) +
 *         theme/parts/*.html + theme/templates/*.html
 * Output: the same files with over-budget motion classes removed, plus
 *         logs/motion-sanity.txt listing every removal.
 *
 * Sections are generated by independent concurrent LLM calls, so nothing
 * upstream enforces site-level motion coherence — one section could take
 * three effects while four take none, or every section could claim the one
 * ambient "signature" slot. The section prompt states the budget; this step
 * is the deterministic backstop. It only ever REMOVES class tokens, never
 * adds them:
 *  - unknown motion-flavored classes (invented `reveal-left` variants and the
 *    JS-owned `is-visible` state class) — they have no CSS, or fight the kit;
 *  - classes the committed motion profile disallows (`minimal` keeps hover
 *    effects only; `none` strips every motion class);
 *  - ambient classes and `hero-entrance` beyond the FIRST one on the page
 *    (sections are visited in page order, so the earliest — usually the
 *    hero — keeps its effect);
 *  - extra kit classes beyond the first on a single block, and
 *    `stagger-children` on containers without at least two child blocks.
 *
 * Runs BEFORE fix-blocks on purpose (same rationale as contrast-fix): edits
 * rewrite only the block-comment JSON attributes, and the fix-blocks
 * re-serialization regenerates the saved HTML from those attributes. The
 * stripped tokens are ALSO removed from each block's own class="…" HTML —
 * otherwise the fixer's fixCustomClassname would rescue the stale token from
 * the saved HTML right back into className.
 */
final class MotionSanityStep implements Step
{
    private const REPORT_FILE = 'motion-sanity.txt';

    public function id(): string
    {
        return 'motion-sanity';
    }

    public function label(): string
    {
        return 'Motion sanity pass';
    }

    public function run(Project $project): void
    {
        $profile = DesignDirectionStep::motionProfileFor($project);
        $budget = self::newBudget();
        $report = [];

        foreach (self::filesInPageOrder($project) as $rel) {
            $markup = $project->readText('theme/' . $rel);
            $result = self::sanitize($markup, $profile, $budget);
            if ($result['markup'] !== $markup) {
                $project->writeText('theme/' . $rel, $result['markup']);
            }
            foreach ($result['notes'] as $note) {
                $report[] = "[{$rel}] {$note}";
            }
        }

        if ($report === []) {
            $report[] = "Motion profile '{$profile}': all motion classes within budget.";
        }
        $project->writeText('logs/' . self::REPORT_FILE, implode("\n", $report) . "\n");

        $removed = count($report) - (str_starts_with($report[0], 'Motion profile') ? 1 : 0);
        echo sprintf(
            "  motion: profile '%s', %d class(es) stripped (details: logs/%s)\n",
            $profile, $removed, self::REPORT_FILE
        );
    }

    /**
     * Fresh page-level budget state, threaded through sanitize() calls so the
     * one-per-page limits span every file of the page.
     *
     * @return array{ambient:int, hero:int}
     */
    public static function newBudget(): array
    {
        return ['ambient' => 0, 'hero' => 0];
    }

    /**
     * Section parts in plan order first (the page-level "first ambient wins"
     * budget should favor the hero, not whichever filename globs first), then
     * the chrome parts and any remaining files.
     *
     * @return string[] theme-relative paths
     */
    public static function filesInPageOrder(Project $project): array
    {
        $all = FixBlocksStep::themeFiles($project);

        $planned = [];
        if ($project->exists('sections.json')) {
            foreach (($project->readJson('sections.json')['sections'] ?? []) as $section) {
                $slug = trim((string) ($section['slug'] ?? ''));
                if ($slug !== '') {
                    $planned[] = 'parts/' . SectionsStep::SECTION_PREFIX . $slug . '.html';
                }
            }
        }

        $ordered = array_values(array_intersect($planned, $all));
        foreach ($all as $rel) {
            if (!in_array($rel, $ordered, true)) {
                $ordered[] = $rel;
            }
        }
        return $ordered;
    }

    /**
     * Strip over-budget motion classes from one document. Removal-only: the
     * kept class list is always a subset of the authored one. $budget carries
     * the page-level counters across files. Pure — unit-testable.
     *
     * @param array{ambient:int, hero:int} $budget
     * @return array{markup:string, notes:string[]}
     */
    public static function sanitize(string $markup, string $profile, array &$budget): array
    {
        $doc = BlockMarkup::parse($markup);
        $allowed = Motion::allowedClasses($profile);
        $notes = [];

        foreach ($doc->indices() as $i) {
            $attrs = $doc->attrs($i);
            $className = $attrs['className'] ?? null;
            if (!is_string($className) || trim($className) === '') {
                continue;
            }

            $kept = [];
            $dropped = [];
            $kitOnBlock = 0;
            foreach (preg_split('/\s+/', trim($className)) ?: [] as $token) {
                $verdict = self::verdict($token, $allowed, $kitOnBlock, $budget, $doc, $i);
                if ($verdict === null) {
                    $kept[] = $token;
                    continue;
                }
                $dropped[] = $token;
                $notes[] = "{$doc->name($i)}: dropped '{$token}' ({$verdict})";
            }

            if ($dropped === []) {
                continue;
            }

            if ($kept === []) {
                unset($attrs['className']);
            } else {
                $attrs['className'] = implode(' ', $kept);
            }
            $doc->setAttrs($i, $attrs);

            // Also remove each token from the block's own class="…" HTML.
            // Exact-token boundaries (space or quote on both sides) so
            // 'reveal' never eats into 'reveal-up'.
            foreach ($dropped as $token) {
                $doc->replaceInOwnHtml($i, " {$token} ", ' ');
                $doc->replaceInOwnHtml($i, "\"{$token} ", '"');
                $doc->replaceInOwnHtml($i, " {$token}\"", '"');
                $doc->replaceInOwnHtml($i, "\"{$token}\"", '""');
            }
        }

        return ['markup' => $doc->render(), 'notes' => $notes];
    }

    /**
     * Why one class token must be dropped, or null to keep it. Mutates the
     * per-block kit counter and the page-level budget when a budgeted class
     * is KEPT.
     *
     * @param string[] $allowed
     * @param array{ambient:int, hero:int} $budget
     */
    private static function verdict(
        string $token,
        array $allowed,
        int &$kitOnBlock,
        array &$budget,
        BlockMarkup $doc,
        int $i,
    ): ?string {
        if (!Motion::looksLikeMotionClass($token)) {
            return null; // not a motion class — none of our business
        }
        if ($token === Motion::STATE_CLASS) {
            return 'JS-owned state class; never authored';
        }

        $isKit = in_array($token, Motion::kitClasses(), true);
        $isHover = in_array($token, Motion::HOVER_CLASSES, true);
        if (!$isKit && !$isHover) {
            return 'unknown motion class — no CSS ships for it';
        }
        if (!in_array($token, $allowed, true)) {
            return "disallowed by the motion profile";
        }
        if ($isHover) {
            return null; // hover effects don't count toward any budget
        }

        if ($kitOnBlock >= 1) {
            return 'a block gets at most one motion class';
        }
        if ($token === 'stagger-children' && count($doc->children($i)) < 2) {
            return 'stagger-children needs a container with at least two children';
        }
        if (in_array($token, Motion::AMBIENT_CLASSES, true)) {
            if ($budget['ambient'] >= 1) {
                return 'ambient budget: one signature effect per page';
            }
            $budget['ambient']++;
        }
        if ($token === 'hero-entrance') {
            if ($budget['hero'] >= 1) {
                return 'hero-entrance budget: once per page';
            }
            $budget['hero']++;
        }

        $kitOnBlock++;
        return null;
    }
}
