<?php
declare(strict_types=1);

namespace Automattic\SiteBuild\Units;

use Automattic\SiteBuild\BlockDocumentRecovery;
use Automattic\SiteBuild\BlockMarkup;
use Automattic\SiteBuild\MarkupSalvage;
use Automattic\SiteBuild\MarkupSanitizer;
use Automattic\SiteBuild\Narrator;

/** Project-free normalization shared by every generated markup unit. */
final class GeneratedMarkup
{
    /**
     * Strip an accidental code fence, require block markup, repair common
     * malformed preset references, strip script-capable markup, and salvage a
     * truncated response back to its last complete block. Every part is
     * untrusted model output headed for templates and stored post content, so
     * this is the one intake it all passes through.
     *
     * $warnings receives one actionable row per removal or degradation that
     * changed delivered content (sanitizer strips, wrapper recovery, lossy
     * truncation salvage). Callers with a Project route them to warnings.json;
     * every note is also narrated for live visibility.
     *
     * $repairs receives structured rows for semantics-preserving fixes. Those
     * rows belong in a step report or narration, never warnings.json.
     *
     * @param list<string>              $warnings
     * @param list<array<string,mixed>> $repairs
     */
    public static function normalize(
        string $text,
        string $key,
        array &$warnings = [],
        array &$repairs = []
    ): string
    {
        $record = static function (string $note) use ($key, &$warnings): void {
            Narrator::write("    (part '{$key}': {$note})\n");
            $warnings[] = "file='theme/parts/{$key}.html'; block='generated part intake'; authored="
                . (string) json_encode($note, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
                . '; delivered="normalized surviving markup"; disposition=unsafe, incomplete, or displaced '
                . 'generated bytes were removed at the smallest safe intake boundary and the usable part continued';
        };

        // Sanitize the whole response before looking for a document boundary:
        // block-looking comments inside a script body are not payload.
        $sanitizerNotes = [];
        $trimmed = trim($text);
        $unfenced = self::stripFences($trimmed);
        if ($unfenced !== $trimmed) {
            $repairs[] = [
                'code' => 'response-fence-removed',
                'part' => $key,
                'disposition' => 'repaired',
            ];
        }
        $text = MarkupSanitizer::sanitize($unfenced, $sanitizerNotes);
        foreach ($sanitizerNotes as $note) {
            $record("sanitized script-capable markup — {$note}");
        }

        // A single dropped `}` in one delimiter's attribute JSON otherwise
        // poisons every containing frame and discards the whole part. Closing
        // the object is bounded and idempotent; a key that consequently lands
        // one nesting level deep is ignored by WordPress, which is strictly
        // better than losing the section.
        $attrsRepairs = [];
        $text = self::closeUnbalancedDelimiterAttrs($text, $attrsRepairs);
        foreach ($attrsRepairs as $note) {
            Narrator::write("    (part '{$key}': {$note})\n");
            $repairs[] = [
                'code' => 'delimiter-attrs-braces-closed',
                'part' => $key,
                'authored' => $note,
                'delivered' => 'parseable delimiter attributes',
                'disposition' => 'repaired',
            ];
        }

        $recoveryNotes = [];
        try {
            $markup = BlockDocumentRecovery::recover($text, $recoveryNotes);
        } catch (\RuntimeException $e) {
            throw new \RuntimeException("part '{$key}': {$e->getMessage()}");
        }
        foreach ($recoveryNotes as $note) {
            $record($note);
        }
        $markup = rtrim($markup);
        $normalizedPresets = self::normalizePresetRefs($markup);
        if ($normalizedPresets !== $markup) {
            $repairs[] = [
                'code' => 'preset-reference-canonicalized',
                'part' => $key,
                'disposition' => 'repaired',
            ];
        }
        $markup = $normalizedPresets;

        // A response cut off by the output-token ceiling (or otherwise left
        // structurally unclosed) is trimmed to its last complete block rather
        // than accepted broken — it would only fail the build much later, at
        // the section-rhythm root-group gate, after every other part was paid
        // for.
        try {
            $salvage = MarkupSalvage::repair($markup);
        } catch (\RuntimeException $e) {
            throw new \RuntimeException("part '{$key}': {$e->getMessage()}");
        }
        foreach ($salvage['warnings'] as $note) {
            $record($note);
        }
        foreach ($salvage['repairs'] as $note) {
            Narrator::write("    (part '{$key}': {$note})\n");
            $repairs[] = [
                'code' => 'truncated-markup-repaired',
                'part' => $key,
                'authored' => $note,
                'delivered' => 'complete block markup',
                'disposition' => 'repaired',
            ];
        }

        try {
            BlockDocumentRecovery::assertComplete($salvage['markup']);
        } catch (\RuntimeException $e) {
            throw new \RuntimeException("part '{$key}': {$e->getMessage()}");
        }
        return $salvage['markup'];
    }

    /**
     * Ensure a header/footer top-level wp:group declares a constrained layout.
     * An explicit layout is preserved.
     */
    public static function constrainedPart(string $markup): string
    {
        if (preg_match('/^<!--\s*wp:group\s*(\{.*?\})?\s*-->/s', $markup, $m) !== 1) {
            return $markup;
        }
        $attrs = isset($m[1]) && $m[1] !== '' ? json_decode($m[1], true) : [];
        if (!is_array($attrs) || isset($attrs['layout'])) {
            return $markup;
        }
        $attrs['layout'] = ['type' => 'constrained'];
        $json = json_encode($attrs, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        return '<!-- wp:group ' . $json . ' -->' . substr($markup, strlen($m[0]));
    }

    /**
     * Give a generated part exactly one root wp:group and one assigned marker
     * from a class family, preserving every unrelated class token.
     *
     * Complete multiple roots and a complete single non-group root are wrapped
     * instead of discarded. The original block document remains a byte-for-byte
     * substring of that envelope. Both the block attribute and saved root HTML
     * are synchronized so later block re-serialization cannot resurrect a
     * stale recipe marker.
     *
     * @param list<array<string,mixed>> $repairs
     */
    public static function withRootClassMarker(
        string $markup,
        string $markerPrefix,
        string $assignedMarker,
        string $part,
        array &$repairs = []
    ): string {
        if (
            preg_match('/^[a-z0-9_-]+--$/', $markerPrefix) !== 1
            || preg_match('/^[a-z0-9_-]+$/', $assignedMarker) !== 1
            || !str_starts_with($assignedMarker, $markerPrefix)
        ) {
            throw new \InvalidArgumentException('invalid assigned root class marker');
        }

        $document = BlockMarkup::parse($markup);
        $roots = array_values(array_filter(
            $document->indices(),
            static fn (int $index): bool => $document->parent($index) === null
        ));
        if ($roots === []) {
            throw new \RuntimeException("part '{$part}': generated markup has no root block");
        }

        if (count($roots) !== 1 || $document->name($roots[0]) !== 'group') {
            $authored = count($roots) === 1 ? $document->name($roots[0]) : count($roots) . ' roots';
            $markup = '<!-- wp:group -->' . "\n"
                . '<div class="wp-block-group">' . "\n"
                . $markup . "\n"
                . '</div>' . "\n"
                . '<!-- /wp:group -->';
            $repairs[] = [
                'code' => 'root-group-wrapped',
                'part' => $part,
                'authored' => $authored,
                'delivered' => 'one wp:group root',
                'disposition' => 'repaired',
            ];
            $document = BlockMarkup::parse($markup);
            $roots = array_values(array_filter(
                $document->indices(),
                static fn (int $index): bool => $document->parent($index) === null
            ));
        }

        $root = $roots[0] ?? null;
        if ($root === null || count($roots) !== 1 || $document->name($root) !== 'group') {
            throw new \RuntimeException("part '{$part}': could not establish one wp:group root");
        }

        $attrs = $document->attrs($root) ?? [];
        $authoredAttributeClasses = is_string($attrs['className'] ?? null)
            ? self::classTokens($attrs['className'])
            : [];
        $deliveredAttributeClasses = self::replaceMarkerTokens(
            $authoredAttributeClasses,
            $markerPrefix,
            $assignedMarker
        );
        if ($deliveredAttributeClasses === []) {
            unset($attrs['className']);
        } else {
            $attrs['className'] = implode(' ', $deliveredAttributeClasses);
        }
        if ($authoredAttributeClasses !== $deliveredAttributeClasses) {
            $document->setAttrs($root, $attrs);
            $markup = $document->render();

            // Reparse after the comment mutation so offsets describe current bytes.
            $document = BlockMarkup::parse($markup);
            $root = $document->topLevel();
        }
        if ($root === null || $document->name($root) !== 'group') {
            throw new \RuntimeException("part '{$part}': root group disappeared during marker repair");
        }
        $ownHtml = $document->ownHtml($root);
        if (preg_match(
            '~\A(?:(?:\s+)|(?:<!--(?:(?!-->).)*-->))*(?<tag><[a-z][a-z0-9:-]*(?=[\s>])'
                . '(?:[^>"\']+|"[^"]*"|\'[^\']*\')*>)~is',
            $ownHtml,
            $opening,
            PREG_OFFSET_CAPTURE
        ) !== 1) {
            $withoutComments = preg_replace('~<!--(?:(?!-->).)*-->~s', '', $ownHtml);
            if (is_string($withoutComments) && trim($withoutComments) === '') {
                // Wrapperless block markup can still be serialized from the
                // canonical comment attributes by the normal block fixer.
                if ($authoredAttributeClasses !== $deliveredAttributeClasses) {
                    self::recordMarkerRepair(
                        $repairs,
                        $part,
                        $markerPrefix,
                        $authoredAttributeClasses,
                        $assignedMarker
                    );
                }
                return $markup;
            }
            throw new \RuntimeException("part '{$part}': root group has no safe saved HTML wrapper");
        }

        $tag = $opening['tag'][0];
        $classes = self::htmlAttributes($tag, 'class');
        $authoredHtmlClasses = $classes === [] ? [] : self::classTokens($classes[0]['value']);
        $deliveredHtmlClasses = self::replaceMarkerTokens(
            $authoredHtmlClasses,
            $markerPrefix,
            $assignedMarker
        );
        $htmlChanged = $classes === []
            || $authoredHtmlClasses !== $deliveredHtmlClasses
            || count($classes) > 1;
        if ($htmlChanged) {
            for ($index = count($classes) - 1; $index >= 0; $index--) {
                $class = $classes[$index];
                $replacement = $index === 0
                    ? ' class="' . htmlspecialchars(
                        implode(' ', $deliveredHtmlClasses),
                        ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE,
                        'UTF-8'
                    ) . '"'
                    : '';
                $tag = substr_replace(
                    $tag,
                    $replacement,
                    $class['attributeOffset'],
                    strlen($class['attribute'])
                );
            }
            if ($classes === []) {
                $tag = substr_replace(
                    $tag,
                    ' class="' . $assignedMarker . '"',
                    strrpos($tag, '>'),
                    0
                );
            }

            $tagStart = $document->openingOffset($root)
                + $document->openingLength($root)
                + $opening['tag'][1];
            $markup = substr_replace($markup, $tag, $tagStart, strlen($opening['tag'][0]));
        }

        if (
            $authoredAttributeClasses !== $deliveredAttributeClasses
            || $htmlChanged
        ) {
            self::recordMarkerRepair(
                $repairs,
                $part,
                $markerPrefix,
                array_values(array_unique(array_merge($authoredAttributeClasses, $authoredHtmlClasses))),
                $assignedMarker
            );
        }

        return $markup;
    }

    /**
     * Add one exact class token to both a root group's comment attributes and
     * saved HTML. Used for contract-owned behavior hooks that are single
     * tokens rather than a replaceable marker family.
     *
     * @param list<array<string,mixed>> $repairs
     */
    public static function withRootClassToken(
        string $markup,
        string $token,
        string $part,
        array &$repairs = [],
    ): string {
        if (preg_match('/^[a-z0-9_-]+$/', $token) !== 1) {
            throw new \InvalidArgumentException('invalid root class token');
        }
        $document = BlockMarkup::parse($markup);
        $root = $document->topLevel();
        if ($root === null || $document->name($root) !== 'group') {
            throw new \RuntimeException("part '{$part}': root class token requires one wp:group root");
        }
        $changed = false;
        $attrs = $document->attrs($root) ?? [];
        $tokens = self::classTokens((string) ($attrs['className'] ?? ''));
        if (!in_array($token, $tokens, true)) {
            $tokens[] = $token;
            $attrs['className'] = implode(' ', $tokens);
            $document->setAttrs($root, $attrs);
            $markup = $document->render();
            $document = BlockMarkup::parse($markup);
            $root = $document->topLevel();
            $changed = true;
        }
        if ($root === null || $document->name($root) !== 'group') {
            throw new \RuntimeException("part '{$part}': root group disappeared during class-token repair");
        }
        $ownHtml = $document->ownHtml($root);
        if (preg_match(
            '~\A(?:(?:\s+)|(?:<!--(?:(?!-->).)*-->))*(?<tag><[a-z][a-z0-9:-]*(?=[\s>])'
                . '(?:[^>"\']+|"[^"]*"|\'[^\']*\')*>)~is',
            $ownHtml,
            $opening,
            PREG_OFFSET_CAPTURE,
        ) === 1) {
            $tag = $opening['tag'][0];
            $classes = self::htmlAttributes($tag, 'class');
            $htmlTokens = $classes === [] ? [] : self::classTokens($classes[0]['value']);
            if (!in_array($token, $htmlTokens, true)) {
                $htmlTokens[] = $token;
                $replacement = ' class="' . htmlspecialchars(
                    implode(' ', $htmlTokens),
                    ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE,
                    'UTF-8',
                ) . '"';
                if ($classes === []) {
                    $tag = substr_replace($tag, $replacement, strrpos($tag, '>'), 0);
                } else {
                    $tag = substr_replace(
                        $tag,
                        $replacement,
                        $classes[0]['attributeOffset'],
                        strlen($classes[0]['attribute']),
                    );
                }
                $tagStart = $document->openingOffset($root)
                    + $document->openingLength($root)
                    + $opening['tag'][1];
                $markup = substr_replace($markup, $tag, $tagStart, strlen($opening['tag'][0]));
                $changed = true;
            }
        }
        if ($changed) {
            $repairs[] = [
                'code' => 'root-class-token-added',
                'part' => $part,
                'delivered' => $token,
                'disposition' => 'repaired',
            ];
        }
        return $markup;
    }

    /**
     * Reconcile one validated planned primary action against generated hero
     * markup without guessing at arbitrary controls.
     *
     * A unique wp:button anchor at the authoritative destination is safe to
     * identify. Its plain-text label is restored exactly when needed. When a
     * generated control can be identified but carries the wrong destination,
     * only that wp:button is removed. When no action was assigned, every
     * generated wp:button is an unauthorized control and is excised at that
     * block boundary. Ambiguous or omitted planned controls are reported as
     * undelivered so the project-owning parent can atomically null the
     * plan/contract fact or choose a family fallback.
     *
     * @param array{label:string,intent:string,destination:string}|null $action
     * @return array{
     *   markup:string,repairs:list<array<string,mixed>>,warnings:list<string>,delivered:bool
     * }
     */
    public static function reconcilePrimaryAction(
        string $markup,
        ?array $action,
        string $part
    ): array {
        if ($action === null) {
            $buttons = self::buttonBlocks($markup);
            if ($buttons === []) {
                return ['markup' => $markup, 'repairs' => [], 'warnings' => [], 'delivered' => false];
            }
            usort(
                $buttons,
                static fn (array $left, array $right): int => $right['blockOffset'] <=> $left['blockOffset'],
            );
            foreach ($buttons as $button) {
                $markup = substr_replace($markup, '', $button['blockOffset'], $button['blockLength']);
            }
            $authored = json_encode(
                array_map(
                    static fn (array $button): array => [
                        'path' => $button['path'],
                        'markup' => $button['markup'],
                    ],
                    array_reverse($buttons),
                ),
                JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE,
            );
            if (!is_string($authored)) {
                $authored = 'unplanned wp:button block(s)';
            }
            return [
                'markup' => $markup,
                'repairs' => [],
                'warnings' => [
                    "file='parts/{$part}.html'; block='"
                        . implode(', ', array_column(array_reverse($buttons), 'path'))
                        . "'; authored={$authored}; delivered=removed; disposition=no primary action was assigned "
                        . 'to this hero, so only the unplanned wp:button block(s) were removed and sibling content was retained',
                ],
                'delivered' => false,
            ];
        }
        foreach (['label', 'intent', 'destination'] as $field) {
            if (!isset($action[$field]) || !is_string($action[$field]) || trim($action[$field]) === '') {
                throw new \InvalidArgumentException("primary action '{$field}' must be a non-empty string");
            }
        }

        $buttons = self::buttonAnchors($markup);
        $destinationMatches = array_values(array_filter(
            $buttons,
            static fn (array $button): bool => $button['href'] === $action['destination']
        ));
        $labelMatches = array_values(array_filter(
            $buttons,
            static fn (array $button): bool => html_entity_decode(
                strip_tags($button['label']),
                ENT_QUOTES | ENT_HTML5,
                'UTF-8'
            ) === $action['label']
        ));
        $exactMatches = array_values(array_filter(
            $buttons,
            static fn (array $button): bool => $button['href'] === $action['destination']
                && html_entity_decode(
                    strip_tags($button['label']),
                    ENT_QUOTES | ENT_HTML5,
                    'UTF-8'
                ) === $action['label']
        ));
        $candidates = [];
        foreach (array_merge($destinationMatches, $labelMatches) as $candidate) {
            $candidates[(string) $candidate['blockOffset']] = $candidate;
        }
        $candidates = array_values($candidates);

        // One exact visitor-facing pair is authoritative even when an
        // unrelated secondary control happens to share its destination. The
        // destination-only control is not ours to rewrite or remove. A second
        // control reusing the authoritative label for another destination is
        // identifiable generated drift, however, so isolate that control and
        // keep the canonical pair delivered.
        if (count($exactMatches) === 1 && $exactMatches[0]['simple']) {
            $exactOffset = $exactMatches[0]['blockOffset'];
            $conflictingLabelMatches = array_values(array_filter(
                $labelMatches,
                static fn (array $button): bool => $button['blockOffset'] !== $exactOffset
            ));
            if ($conflictingLabelMatches !== []) {
                return self::removePrimaryActionButtons(
                    $markup,
                    $conflictingLabelMatches,
                    $action,
                    $part,
                    'the authoritative action remained delivered, but another generated button reused its label for a non-authoritative destination',
                    true,
                );
            }
            return ['markup' => $markup, 'repairs' => [], 'warnings' => [], 'delivered' => true];
        }

        if (count($destinationMatches) === 1 && count($candidates) === 1) {
            $button = $destinationMatches[0];
            if (!$button['simple']) {
                return self::removePrimaryActionButtons(
                    $markup,
                    [$button],
                    $action,
                    $part,
                    'the unique destination-matching action used non-plain nested label markup'
                );
            }

            $authoredLabel = html_entity_decode(
                $button['label'],
                ENT_QUOTES | ENT_HTML5,
                'UTF-8'
            );
            if ($authoredLabel === $action['label']) {
                return ['markup' => $markup, 'repairs' => [], 'warnings' => [], 'delivered' => true];
            }

            $replacement = htmlspecialchars(
                $action['label'],
                ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE,
                'UTF-8'
            );
            $markup = substr_replace(
                $markup,
                $replacement,
                $button['labelOffset'],
                $button['labelLength']
            );
            return [
                'markup' => $markup,
                'repairs' => [[
                    'code' => 'primary-action-label-restored',
                    'part' => $part,
                    'path' => $button['path'],
                    'authored' => $authoredLabel,
                    'delivered' => $action['label'],
                    'disposition' => 'repaired',
                ]],
                'warnings' => [],
                'delivered' => true,
            ];
        }

        if ($candidates !== []) {
            $reason = count($candidates) > 1
                ? 'multiple generated buttons matched the authoritative primary-action label or destination'
                : 'the planned action label was attached to a non-authoritative destination';
            return self::removePrimaryActionButtons(
                $markup,
                $candidates,
                $action,
                $part,
                $reason
            );
        }

        $authored = json_encode($action, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if (!is_string($authored)) {
            $authored = get_debug_type($action);
        }
        return [
            'markup' => $markup,
            'repairs' => [],
            'warnings' => [
                "file='parts/{$part}.html'; block='planned primary action'; authored={$authored}; "
                    . 'delivered=removed; disposition=the generated hero omitted the action or made it ambiguous, '
                    . 'so no control was guessed and the parent must null the delivered plan/contract action',
            ],
            'delivered' => false,
        ];
    }

    /**
     * Report whether the exact authoritative pair is delivered by one simple
     * wp:button control. This intentionally shares the same structural domain
     * as reconcilePrimaryAction(); an arbitrary paragraph link cannot revive
     * an action that the unit finisher rejected.
     *
     * @param array{label:string,intent:string,destination:string} $action
     */
    public static function containsPrimaryAction(string $markup, array $action): bool
    {
        foreach (['label', 'intent', 'destination'] as $field) {
            if (!isset($action[$field]) || !is_string($action[$field]) || trim($action[$field]) === '') {
                return false;
            }
        }
        foreach (self::buttonAnchors($markup) as $button) {
            $label = html_entity_decode(
                strip_tags($button['label']),
                ENT_QUOTES | ENT_HTML5,
                'UTF-8',
            );
            if ($button['simple']
                && $button['href'] === $action['destination']
                && $label === $action['label']
            ) {
                return true;
            }
        }
        return false;
    }

    /**
     * Remove only wp:button blocks identifiable as one authoritative action.
     * Used when delivered-page/anchor facts invalidate an action after the
     * hero was already authored. Unrelated links and sibling blocks are left
     * byte-for-byte unchanged.
     *
     * @param array{label:string,intent:string,destination:string} $action
     * @return array{
     *   markup:string,repairs:list<array<string,mixed>>,warnings:list<string>,delivered:bool
     * }
     */
    public static function withoutPrimaryAction(string $markup, array $action, string $part): array
    {
        foreach (['label', 'intent', 'destination'] as $field) {
            if (!isset($action[$field]) || !is_string($action[$field]) || trim($action[$field]) === '') {
                throw new \InvalidArgumentException("primary action '{$field}' must be a non-empty string");
            }
        }
        $candidates = [];
        foreach (self::buttonAnchors($markup) as $button) {
            $label = html_entity_decode(
                strip_tags($button['label']),
                ENT_QUOTES | ENT_HTML5,
                'UTF-8',
            );
            if ($button['href'] === $action['destination'] || $label === $action['label']) {
                $candidates[(string) $button['blockOffset']] = $button;
            }
        }
        if ($candidates === []) {
            return ['markup' => $markup, 'repairs' => [], 'warnings' => [], 'delivered' => false];
        }
        return self::removePrimaryActionButtons(
            $markup,
            array_values($candidates),
            $action,
            $part,
            'the delivered page/anchor set invalidated the authoritative destination',
        );
    }

    /**
     * Remove a redundant header/footer landmark from a generated template part.
     *
     * The template-part block already supplies the semantic landmark. When the
     * generated part repeats it on any wp:group, WordPress renders nested
     * <header> or <footer> elements. Every matching group is normalized while
     * unrelated attributes, child markup, and unknown tag names stay untouched.
     *
     * A mutation is transactional at the group boundary: its literal wrapper
     * must already be a valid div pair, or both matching landmark tags must be
     * available for rewriting. Malformed or mismatched pairs keep their
     * tagName and source bytes for downstream degradation. Operations are
     * applied back-to-front, and a second pass is byte-for-byte stable.
     */
    public static function withoutRedundantLandmark(string $markup, string $landmark): string
    {
        if (!in_array($landmark, ['header', 'footer'], true)) {
            return $markup;
        }

        $document = BlockMarkup::parse($markup);
        $tag = preg_quote($landmark, '~');
        $openingPattern = '~\A(\s*)<(?<tag>div|' . $tag
            . ')(?=[\s>])(?:[^>"\']+|"[^"]*"|\'[^\']*\')*>~is';
        $closingPattern = '~</(?<tag>div|' . $tag . ')\s*>(\s*)\z~is';
        $operations = [];

        foreach ($document->indices() as $index) {
            if (
                $document->name($index) !== 'group'
                || $document->endOffset($index) === null
            ) {
                continue;
            }

            $attrs = $document->attrs($index);
            if (!is_array($attrs) || ($attrs['tagName'] ?? null) !== $landmark) {
                continue;
            }

            $inner = $document->innerHtml($index);
            if (
                preg_match($openingPattern, $inner, $opening, PREG_OFFSET_CAPTURE) !== 1
                || preg_match($closingPattern, $inner, $closing, PREG_OFFSET_CAPTURE) !== 1
            ) {
                continue;
            }

            $openingTag = strtolower($opening['tag'][0]);
            $closingTag = strtolower($closing['tag'][0]);
            if ($openingTag !== $closingTag) {
                continue;
            }

            unset($attrs['tagName']);
            $operations[] = [
                'start' => $document->openingOffset($index),
                'length' => $document->openingLength($index),
                'replacement' => BlockMarkup::serializeComment('group', $attrs, false),
            ];

            if ($openingTag === 'div') {
                continue;
            }

            $innerStart = $document->openingOffset($index) + $document->openingLength($index);
            $operations[] = [
                'start' => $innerStart + $opening[0][1],
                'length' => strlen($opening[0][0]),
                'replacement' => (string) preg_replace(
                    '~<' . $tag . '(?=[\s>])~i',
                    '<div',
                    $opening[0][0],
                    1
                ),
            ];
            $operations[] = [
                'start' => $innerStart + $closing[0][1],
                'length' => strlen($closing[0][0]),
                'replacement' => (string) preg_replace(
                    '~</' . $tag . '\s*>~i',
                    '</div>',
                    $closing[0][0],
                    1
                ),
            ];
        }

        usort($operations, static fn (array $a, array $b): int => $b['start'] <=> $a['start']);
        foreach ($operations as $operation) {
            $markup = substr_replace(
                $markup,
                $operation['replacement'],
                $operation['start'],
                $operation['length']
            );
        }

        return $markup;
    }

    /**
     * Require the template part to rely on its surrounding landmark wrapper.
     *
     * Called after withoutRedundantLandmark(): any matching group attribute or
     * literal element left at that point was not structurally safe to repair,
     * so the owning step can deliver its deterministic chrome fallback rather
     * than ship nested or malformed landmarks.
     */
    public static function assertNoRedundantLandmark(string $markup, string $landmark): void
    {
        if (!in_array($landmark, ['header', 'footer'], true)) {
            throw new \InvalidArgumentException("unsupported template-part landmark '{$landmark}'");
        }

        $document = BlockMarkup::parse($markup);
        foreach ($document->indices() as $index) {
            $attrs = $document->attrs($index);
            if (
                $document->name($index) === 'group'
                && is_array($attrs)
                && ($attrs['tagName'] ?? null) === $landmark
            ) {
                throw new \RuntimeException("contains an unrepaired nested {$landmark} landmark");
            }
        }
        if (preg_match('~</?' . preg_quote($landmark, '~') . '(?=[\s>])~i', $markup) === 1) {
            throw new \RuntimeException("contains a literal nested {$landmark} landmark");
        }
    }

    /**
     * A one-page footer's dynamic site-title must not render a link back to
     * the page the visitor is already viewing. Apply the explicit attribute to
     * every generated site-title so a nested lockup cannot evade the rule.
     */
    public static function withoutSiteTitleLinks(string $markup): string
    {
        $document = BlockMarkup::parse($markup);
        foreach ($document->indices() as $index) {
            if ($document->name($index) !== 'site-title') {
                continue;
            }
            $attrs = $document->attrs($index) ?? [];
            $attrs['isLink'] = false;
            $document->setAttrs($index, $attrs);
        }
        return $document->render();
    }

    /**
     * Cap footer AI_IMAGE placeholders to non-portrait aspect ratios.
     *
     * A `portrait` placeholder generates a 9:16 asset; rendered in a footer
     * column it grows nearly twice as tall as wide, stretches the whole band,
     * and strands blank space beside the short utility rows. The documented
     * `<img alt>` form and any mirrored block-JSON "alt" value are rewritten
     * together so block re-serialization cannot restore the portrait spec.
     * Idempotent: a capped placeholder no longer matches either pattern.
     *
     * @param list<string> $notes appended to once per rewritten placeholder
     */
    public static function withoutPortraitImagePlaceholders(string $markup, array &$notes = []): string
    {
        $patterns = [
            '/(?<prefix>alt\s*=\s*(?<quote>["\'])AI_IMAGE:(?:(?!\k{quote}).)*?\|\s*)portrait(?<suffix>\s*\k{quote})/is',
            '/(?<prefix>"alt"\s*:\s*"AI_IMAGE:(?:[^"\\\\]|\\\\.)*?\|\s*)portrait(?<suffix>\s*")/is',
        ];
        foreach ($patterns as $pattern) {
            $markup = (string) preg_replace_callback(
                $pattern,
                static function (array $m) use (&$notes): string {
                    $notes[] = "file='parts/footer.html'; block='AI_IMAGE placeholder'; "
                        . 'authored aspect-ratio=portrait; delivered=square; '
                        . 'disposition=a 9:16 footer image stretches the band and strands blank '
                        . 'space beside the utility rows, so the placeholder was capped to square';
                    return $m['prefix'] . 'square' . $m['suffix'];
                },
                $markup
            );
        }
        return $markup;
    }

    /**
     * Enforce the concrete surface shared by the footer and closing sections.
     *
     * The comment attribute is the source of truth consumed by downstream
     * layout/contrast passes. Multiple generated roots — or a single root that
     * is not a wp:group — are wrapped without dropping content, and any saved
     * root element is synchronized as well so stale generated classes/styles
     * cannot be sourced back into the block before re-serialization.
     *
     * @param list<string> $notes appended to when opaque authored styling must
     *                            be removed to make the surface enforceable
     */
    public static function withRootBackgroundColor(
        string $markup,
        string $color,
        array &$notes = [],
        string $part = 'footer',
    ): string
    {
        if (preg_match('/^[a-z0-9-]+$/', $color) !== 1) {
            throw new \InvalidArgumentException("invalid root background color slug '{$color}'");
        }

        $document = BlockMarkup::parse($markup);
        $roots = array_values(array_filter(
            $document->indices(),
            static fn (int $index): bool => $document->parent($index) === null
        ));
        if (
            $roots !== []
            && (count($roots) > 1 || $document->name($roots[0]) !== 'group')
        ) {
            $markup = '<!-- wp:group -->' . "\n"
                . '<div class="wp-block-group">' . "\n"
                . $markup . "\n"
                . '</div>' . "\n"
                . '<!-- /wp:group -->';
            $document = BlockMarkup::parse($markup);
            $roots = array_values(array_filter(
                $document->indices(),
                static fn (int $index): bool => $document->parent($index) === null
            ));
        }
        $root = $roots[0] ?? null;
        if ($root === null || $document->name($root) !== 'group') {
            throw new \RuntimeException("{$part} root is not a wp:group");
        }
        $attrs = $document->attrs($root) ?? [];

        unset($attrs['gradient']);
        if (array_key_exists('style', $attrs) && !is_array($attrs['style'])) {
            self::recordRemovedRootStyle($notes, $part, 'style', $attrs['style'], $color);
            unset($attrs['style']);
        } elseif (is_array($attrs['style'] ?? null)) {
            unset($attrs['style']['background']);
            if (array_key_exists('color', $attrs['style']) && !is_array($attrs['style']['color'])) {
                self::recordRemovedRootStyle($notes, $part, 'style.color', $attrs['style']['color'], $color);
                unset($attrs['style']['color']);
            } elseif (is_array($attrs['style']['color'] ?? null)) {
                unset($attrs['style']['color']['background'], $attrs['style']['color']['gradient']);
                if ($attrs['style']['color'] === []) {
                    unset($attrs['style']['color']);
                }
            }
            foreach (['css', 'variation'] as $opaqueStyle) {
                if (!array_key_exists($opaqueStyle, $attrs['style'])) {
                    continue;
                }
                self::recordRemovedRootStyle(
                    $notes,
                    $part,
                    "style.{$opaqueStyle}",
                    $attrs['style'][$opaqueStyle],
                    $color
                );
                unset($attrs['style'][$opaqueStyle]);
            }
            if ($attrs['style'] === []) {
                unset($attrs['style']);
            }
        }
        if (is_string($attrs['className'] ?? null)) {
            $tokens = self::withoutBackgroundClassTokens($attrs['className']);
            if ($tokens === []) {
                unset($attrs['className']);
            } else {
                $attrs['className'] = implode(' ', $tokens);
            }
        }
        $attrs['backgroundColor'] = $color;
        $document->setAttrs($root, $attrs);
        $markup = $document->render();

        $document = BlockMarkup::parse($markup);
        $root = $document->topLevel();
        if ($root === null || $document->name($root) !== 'group') {
            throw new \RuntimeException("{$part} root group disappeared during surface repair");
        }
        $ownHtml = $document->ownHtml($root);
        if (preg_match(
            '~\A(?:(?:\s+)|(?:<!--(?:(?!-->).)*-->))*(?<tag><[a-z][a-z0-9:-]*(?=[\s>])'
                . '(?:[^>"\']+|"[^"]*"|\'[^\']*\')*>)~is',
            $ownHtml,
            $opening,
            PREG_OFFSET_CAPTURE
        ) !== 1) {
            $withoutComments = preg_replace('~<!--(?:(?!-->).)*-->~s', '', $ownHtml);
            if (is_string($withoutComments) && trim($withoutComments) === '') {
                // A wrapperless/comment-only model response is still
                // repairable: fix-blocks will serialize the group wrapper from
                // the enforced attribute later.
                return $markup;
            }
            throw new \RuntimeException("{$part} root has no safe saved HTML wrapper");
        }

        $tag = $opening['tag'][0];
        $classes = self::htmlAttributes($tag, 'class');
        if ($classes !== []) {
            $tokens = self::withoutBackgroundClassTokens($classes[0]['value']);
            $tokens[] = "has-{$color}-background-color";
            $tokens[] = 'has-background';
            $classValue = implode(' ', array_values(array_unique($tokens)));
            for ($index = count($classes) - 1; $index >= 0; $index--) {
                $class = $classes[$index];
                $replacement = $index === 0
                    ? ' class="' . htmlspecialchars(
                        $classValue,
                        ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE,
                        'UTF-8'
                    ) . '"'
                    : '';
                $tag = substr_replace(
                    $tag,
                    $replacement,
                    $class['attributeOffset'],
                    strlen($class['attribute'])
                );
            }
        } else {
            $tag = substr_replace(
                $tag,
                ' class="has-' . $color . '-background-color has-background"',
                strrpos($tag, '>'),
                0
            );
        }

        $styles = self::htmlAttributes($tag, 'style');
        for ($index = count($styles) - 1; $index >= 0; $index--) {
            $style = $styles[$index];
            try {
                $styleValue = self::withoutBackgroundStyleDeclarations($style['value']);
            } catch (\RuntimeException) {
                self::recordRemovedRootStyle(
                    $notes,
                    $part,
                    "saved HTML style attribute[{$index}]",
                    $style['value'],
                    $color
                );
                $styleValue = '';
            }
            $replacement = $styleValue === ''
                ? ''
                : substr_replace(
                    $style['attribute'],
                    $styleValue,
                    $style['valueOffset'] - $style['attributeOffset'],
                    strlen($style['value'])
                );
            $tag = substr_replace(
                $tag,
                $replacement,
                $style['attributeOffset'],
                strlen($style['attribute'])
            );
        }

        $tagStart = $document->openingOffset($root)
            + $document->openingLength($root)
            + $opening['tag'][1];
        return substr_replace($markup, $tag, $tagStart, strlen($opening['tag'][0]));
    }

    /**
     * Synchronize a contract-owned root text preset into block attributes and
     * saved HTML. Only the frozen generated palette's text-color support
     * classes are replaced; unrelated custom classes remain byte-for-byte.
     *
     * @param list<array<string,mixed>> $repairs
     */
    public static function withRootTextColor(
        string $markup,
        string $color,
        string $part,
        array &$repairs = [],
    ): string {
        if (preg_match('/^[a-z0-9-]+$/', $color) !== 1) {
            throw new \InvalidArgumentException("invalid root text color slug '{$color}'");
        }
        $document = BlockMarkup::parse($markup);
        $root = $document->topLevel();
        if ($root === null || $document->name($root) !== 'group') {
            throw new \RuntimeException("part '{$part}': root text color requires one wp:group root");
        }
        $attrs = $document->attrs($root) ?? [];
        $authored = $attrs['textColor'] ?? null;
        $attrs['textColor'] = $color;
        if (is_array($attrs['style']['color'] ?? null)) {
            unset($attrs['style']['color']['text']);
            if ($attrs['style']['color'] === []) {
                unset($attrs['style']['color']);
            }
            if (($attrs['style'] ?? []) === []) {
                unset($attrs['style']);
            }
        }
        $document->setAttrs($root, $attrs);
        $markup = $document->render();

        $document = BlockMarkup::parse($markup);
        $root = $document->topLevel();
        if ($root === null || $document->name($root) !== 'group') {
            throw new \RuntimeException("part '{$part}': root group disappeared during text-color repair");
        }
        $ownHtml = $document->ownHtml($root);
        if (preg_match(
            '~\A(?:(?:\s+)|(?:<!--(?:(?!-->).)*-->))*(?<tag><[a-z][a-z0-9:-]*(?=[\s>])'
                . '(?:[^>"\']+|"[^"]*"|\'[^\']*\')*>)~is',
            $ownHtml,
            $opening,
            PREG_OFFSET_CAPTURE,
        ) !== 1) {
            throw new \RuntimeException("part '{$part}': root group has no safe saved HTML wrapper");
        }

        $tag = $opening['tag'][0];
        $classes = self::htmlAttributes($tag, 'class');
        $tokens = [];
        foreach ($classes as $class) {
            array_push($tokens, ...self::classTokens($class['value']));
        }
        $tokens = array_values(array_filter(
            array_unique($tokens),
            static fn (string $token): bool => $token !== 'has-text-color'
                && preg_match('/^has-(?:base|contrast|primary|secondary|accent)-color$/', $token) !== 1,
        ));
        $tokens[] = "has-{$color}-color";
        $tokens[] = 'has-text-color';
        $classValue = implode(' ', array_values(array_unique($tokens)));
        if ($classes === []) {
            $tag = substr_replace(
                $tag,
                ' class="' . htmlspecialchars($classValue, ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE, 'UTF-8') . '"',
                strrpos($tag, '>'),
                0,
            );
        } else {
            for ($index = count($classes) - 1; $index >= 0; $index--) {
                $class = $classes[$index];
                $replacement = $index === 0
                    ? ' class="' . htmlspecialchars($classValue, ENT_QUOTES | ENT_HTML5 | ENT_SUBSTITUTE, 'UTF-8') . '"'
                    : '';
                $tag = substr_replace(
                    $tag,
                    $replacement,
                    $class['attributeOffset'],
                    strlen($class['attribute']),
                );
            }
        }
        $tagStart = $document->openingOffset($root)
            + $document->openingLength($root)
            + $opening['tag'][1];
        $delivered = substr_replace($markup, $tag, $tagStart, strlen($opening['tag'][0]));
        if ($delivered !== $markup || $authored !== $color) {
            $repairs[] = [
                'code' => 'root-text-color-synchronized',
                'part' => $part,
                'authored' => $authored,
                'delivered' => $color,
                'disposition' => 'repaired',
            ];
        }
        return $delivered;
    }

    /**
     * @return list<array{
     *   href:string,label:string,simple:bool,labelOffset:int,labelLength:int,
     *   blockOffset:int,blockLength:int,path:string
     * }>
     */
    private static function buttonAnchors(string $markup): array
    {
        $document = BlockMarkup::parse($markup);
        $buttons = [];
        $ordinal = 0;
        foreach ($document->indices() as $index) {
            if ($document->name($index) !== 'button') {
                continue;
            }
            $ordinal++;
            $end = $document->endOffset($index);
            if ($end === null) {
                continue;
            }
            $inner = $document->innerHtml($index);
            if (preg_match_all(
                '~(?<opening><a\b(?:[^>"\']+|"[^"]*"|\'[^\']*\')*>)(?<content>.*?)</a\s*>~is',
                $inner,
                $matches,
                PREG_SET_ORDER | PREG_OFFSET_CAPTURE
            ) !== 1) {
                // A wp:button with zero or multiple anchors is not a simple,
                // safely identifiable primary-action control.
                continue;
            }
            $match = $matches[0];
            $opening = $match['opening'][0];
            $href = null;
            foreach (MarkupSanitizer::openingTagAttributes($opening) as $attribute) {
                if (
                    $attribute['name'] !== 'href'
                    || $attribute['valueStart'] === null
                    || $attribute['valueEnd'] === null
                ) {
                    continue;
                }
                $href = substr(
                    $opening,
                    $attribute['valueStart'],
                    $attribute['valueEnd'] - $attribute['valueStart']
                );
                break;
            }
            if (!is_string($href)) {
                $href = '';
            }
            $href = html_entity_decode($href, ENT_QUOTES | ENT_HTML5, 'UTF-8');
            $content = $match['content'][0];
            $innerStart = $document->openingOffset($index) + $document->openingLength($index);
            $buttons[] = [
                'href' => $href,
                'label' => $content,
                'simple' => preg_match('/<[^>]*>/', $content) !== 1,
                'labelOffset' => $innerStart + $match['content'][1],
                'labelLength' => strlen($content),
                'blockOffset' => $document->openingOffset($index),
                'blockLength' => $end - $document->openingOffset($index),
                'path' => "wp:button[{$ordinal}]/a",
            ];
        }
        return $buttons;
    }

    /**
     * @return list<array{blockOffset:int,blockLength:int,path:string,markup:string}>
     */
    private static function buttonBlocks(string $markup): array
    {
        $document = BlockMarkup::parse($markup);
        $buttons = [];
        $ordinal = 0;
        foreach ($document->indices() as $index) {
            if ($document->name($index) !== 'button') {
                continue;
            }
            $ordinal++;
            $end = $document->endOffset($index);
            if ($end === null) {
                continue;
            }
            $offset = $document->openingOffset($index);
            $buttons[] = [
                'blockOffset' => $offset,
                'blockLength' => $end - $offset,
                'path' => "wp:button[{$ordinal}]",
                'markup' => substr($markup, $offset, $end - $offset),
            ];
        }
        return $buttons;
    }

    /**
     * @param list<array{
     *   href:string,label:string,simple:bool,labelOffset:int,labelLength:int,
     *   blockOffset:int,blockLength:int,path:string
     * }> $buttons
     * @param array{label:string,intent:string,destination:string} $action
     * @return array{
     *   markup:string,repairs:list<array<string,mixed>>,warnings:list<string>,delivered:bool
     * }
     */
    private static function removePrimaryActionButtons(
        string $markup,
        array $buttons,
        array $action,
        string $part,
        string $reason,
        bool $actionDelivered = false,
    ): array {
        usort(
            $buttons,
            static fn (array $left, array $right): int => $right['blockOffset'] <=> $left['blockOffset']
        );
        foreach ($buttons as $button) {
            $markup = substr_replace($markup, '', $button['blockOffset'], $button['blockLength']);
        }
        $authored = json_encode(
            [
                'planned' => $action,
                'generated' => array_map(
                    static fn (array $button): array => [
                        'path' => $button['path'],
                        'label' => html_entity_decode(
                            strip_tags($button['label']),
                            ENT_QUOTES | ENT_HTML5,
                            'UTF-8'
                        ),
                        'destination' => $button['href'],
                    ],
                    $buttons
                ),
            ],
            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        );
        if (!is_string($authored)) {
            $authored = get_debug_type($action);
        }
        $paths = implode(', ', array_map(static fn (array $button): string => $button['path'], $buttons));
        return [
            'markup' => $markup,
            'repairs' => [],
            'warnings' => [
                "file='parts/{$part}.html'; block='{$paths}'; authored={$authored}; delivered=removed; "
                    . "disposition={$reason}; only the identifiable primary-action button block was removed",
            ],
            'delivered' => $actionDelivered,
        ];
    }

    /** @return list<string> */
    private static function classTokens(string $classes): array
    {
        $classes = html_entity_decode($classes, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        return array_values(array_unique(
            preg_split('/[\x09\x0A\x0C\x0D\x20]+/', trim($classes), -1, PREG_SPLIT_NO_EMPTY) ?: []
        ));
    }

    /** @param list<string> $tokens @return list<string> */
    private static function replaceMarkerTokens(
        array $tokens,
        string $markerPrefix,
        string $assignedMarker
    ): array {
        $out = [];
        $inserted = false;
        foreach ($tokens as $token) {
            if (!str_starts_with($token, $markerPrefix)) {
                $out[] = $token;
                continue;
            }
            if (!$inserted) {
                // Replace the first family member in place. Keeping the class
                // order stable prevents two independent marker families from
                // moving each other to the end on every fixed-point pass.
                $out[] = $assignedMarker;
                $inserted = true;
            }
        }
        if (!$inserted) {
            $out[] = $assignedMarker;
        }
        return array_values(array_unique($out));
    }

    /**
     * @param list<array<string,mixed>> $repairs
     * @param list<string>              $authoredMarkers
     */
    private static function recordMarkerRepair(
        array &$repairs,
        string $part,
        string $markerPrefix,
        array $authoredMarkers,
        string $assignedMarker
    ): void {
        $repairs[] = [
            'code' => 'root-marker-normalized',
            'part' => $part,
            'path' => 'root wp:group.className',
            'authored' => array_values(array_filter(
                $authoredMarkers,
                static fn (string $token): bool => str_starts_with($token, $markerPrefix)
            )),
            'delivered' => $assignedMarker,
            'disposition' => 'repaired',
        ];
    }

    /**
     * Locate one quoted or unquoted HTML attribute inside an already isolated
     * opening tag.
     *
     * @return list<array{
     *   attribute:string,attributeOffset:int,value:string,valueOffset:int
     * }>
     */
    private static function htmlAttributes(string $tag, string $name): array
    {
        $matches = [];
        foreach (MarkupSanitizer::openingTagAttributes($tag) as $attribute) {
            if (
                $attribute['name'] !== strtolower($name)
                || $attribute['valueStart'] === null
                || $attribute['valueEnd'] === null
            ) {
                continue;
            }
            $valueStart = $attribute['valueStart'];
            $valueEnd = $attribute['valueEnd'];
            $matches[] = [
                'attribute' => substr($tag, $attribute['start'], $attribute['end'] - $attribute['start']),
                'attributeOffset' => $attribute['start'],
                'value' => substr($tag, $valueStart, $valueEnd - $valueStart),
                'valueOffset' => $valueStart,
            ];
        }
        return $matches;
    }

    /** @param list<string> $notes */
    private static function recordRemovedRootStyle(
        array &$notes,
        string $part,
        string $path,
        mixed $authored,
        string $color
    ): void {
        $encoded = json_encode($authored, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if (!is_string($encoded)) {
            $encoded = get_debug_type($authored);
        }
        $notes[] = "file='parts/{$part}.html'; block='root wp:group'; authored {$path}={$encoded}; "
            . "delivered=removed; disposition=opaque or malformed root styling removed so the assigned "
            . "'{$color}' {$part} surface cannot be overridden";
    }

    /** @return list<string> */
    private static function withoutBackgroundClassTokens(string $classes): array
    {
        $classes = html_entity_decode($classes, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        return array_values(array_filter(
            preg_split('/[\x09\x0A\x0C\x0D\x20]+/', trim($classes)) ?: [],
            static fn (string $token): bool => $token !== 'has-background'
                && preg_match('/^has-[a-z0-9-]+-background-color$/', $token) !== 1
                && preg_match('/^has-[a-z0-9-]+-gradient-background$/', $token) !== 1
                && $token !== 'has-background-gradient'
        ));
    }

    /**
     * Remove CSS background declarations without splitting at semicolons in a
     * quoted string, comment, escape, or function argument.
     */
    private static function withoutBackgroundStyleDeclarations(string $style): string
    {
        $declarations = [];
        $start = 0;
        $quote = null;
        $parentheses = 0;
        $inComment = false;
        $length = strlen($style);

        for ($index = 0; $index < $length; $index++) {
            $character = $style[$index];
            if ($inComment) {
                if ($character === '*' && ($style[$index + 1] ?? '') === '/') {
                    $inComment = false;
                    $index++;
                }
                continue;
            }
            if ($quote !== null) {
                if ($character === '\\') {
                    if ($index + 1 >= $length) {
                        throw new \RuntimeException('footer root has a malformed inline style escape');
                    }
                    $index++;
                    continue;
                }
                if ($character === $quote) {
                    $quote = null;
                }
                continue;
            }
            if ($character === '/' && ($style[$index + 1] ?? '') === '*') {
                $inComment = true;
                $index++;
                continue;
            }
            if ($character === '"' || $character === "'") {
                $quote = $character;
                continue;
            }
            if ($character === '\\') {
                if ($index + 1 >= $length) {
                    throw new \RuntimeException('footer root has a malformed inline style escape');
                }
                $index++;
                continue;
            }
            if ($character === '(') {
                $parentheses++;
                continue;
            }
            if ($character === ')') {
                if ($parentheses === 0) {
                    throw new \RuntimeException('footer root has malformed inline style parentheses');
                }
                $parentheses--;
                continue;
            }
            if ($character === ';' && $parentheses === 0) {
                $declarations[] = substr($style, $start, $index - $start);
                $start = $index + 1;
            }
        }
        if ($quote !== null || $inComment || $parentheses !== 0) {
            throw new \RuntimeException('footer root has a malformed inline style');
        }
        $declarations[] = substr($style, $start);

        $kept = [];
        foreach ($declarations as $declaration) {
            $declaration = trim($declaration);
            if ($declaration === '') {
                continue;
            }
            if (preg_match('/^([-\w]+)\s*:/', $declaration, $property) !== 1) {
                throw new \RuntimeException('footer root has a malformed inline style declaration');
            }
            if (str_starts_with(strtolower($property[1]), 'background')) {
                continue;
            }
            $kept[] = $declaration;
        }
        return implode(';', $kept);
    }

    /**
     * Canonicalize preset references to `var:preset|type|slug` in block markup.
     * Models commonly use CSS-style `--` or colon delimiters, sometimes in only
     * one of the two positions. Gutenberg's comment serializer can additionally
     * spell `--` as `\u002d\u002d`. WordPress resolves only the pipe form, so
     * any of those malformed refs produces no style.
     *
     * Match complete prefixes for the fixed preset-type vocabulary instead of
     * replacing dashes globally. This keeps CSS custom properties such as
     * `var(--wp--preset--spacing--xl)` byte-for-byte intact. Pure — testable.
     */
    public static function normalizePresetRefs(string $markup): string
    {
        $types = 'color|gradient|shadow|spacing|font-size|font-family|aspect-ratio|duotone';

        // Each delimiter position independently accepts the pipe, the two
        // model typos (`--` and `:`), and the serializer-escaped spellings
        // `\u002d\u002d` (dash-dash) and `\u007c` (pipe) in either hex case,
        // since JSON permits both. Type names stay case-sensitive.
        $delimiter = '(?:\||:|--|(?:\\\\u002[dD]){2}|\\\\u007[cC])';

        return (string) preg_replace(
            "/var:preset{$delimiter}({$types}){$delimiter}/",
            'var:preset|$1|',
            $markup
        );
    }

    private static function stripFences(string $text): string
    {
        $text = (string) preg_replace('/^\xEF\xBB\xBF/', '', $text);
        if (str_starts_with($text, '```')) {
            $text = preg_replace('/^```[a-zA-Z]*\r?\n/', '', $text);
            $text = preg_replace('/\r?\n```$/', '', (string) $text);
        }
        return trim((string) $text);
    }

    /**
     * Close delimiter attribute objects the model left short of `}`s.
     *
     * Matches the same lazy attrs shape as BlockMarkup::DELIMITER (opening
     * delimiters only). When the captured JSON fails to parse but appending
     * one to three closing braces makes it parse, the delimiter is rewritten
     * in place and a note is recorded. Attributes broken any other way are
     * left untouched for the recovery pass to isolate. Idempotent: repaired
     * attrs parse, so a second pass matches nothing.
     *
     * @param list<string> $notes
     */
    public static function closeUnbalancedDelimiterAttrs(string $text, array &$notes = []): string
    {
        return (string) preg_replace_callback(
            '/(?<head><!--\s+wp:[a-z][a-z0-9_-]*(?:\/[a-z][a-z0-9_-]*)?\s+)'
            . '(?<attrs>\{(?:(?!-->).)*?\})(?<tail>\s+\/?-->)/s',
            static function (array $m) use (&$notes): string {
                $raw = $m['attrs'];
                if (json_decode($raw) !== null || strtolower(trim($raw, "{} \t\r\n")) === 'null') {
                    return $m[0];
                }
                for ($braces = 1; $braces <= 3; $braces++) {
                    $candidate = $raw . str_repeat('}', $braces);
                    if (is_object(json_decode($candidate))) {
                        $notes[] = "closed {$braces} unbalanced attribute brace(s) in "
                            . substr(trim($m['head']), 0, 40) . '…';
                        return $m['head'] . $candidate . $m['tail'];
                    }
                }
                return $m[0];
            },
            $text
        );
    }
}
